using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using BlackjackGame.Config;
using BlackjackGame.Blackjack.Cards;
using BlackjackGame.Core;
using BlackjackGame.UI.Components;
using BlackjackGame.UI.Screens;
using TMPro;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using Object = UnityEngine.Object;

namespace BlackjackGame.EditorTools
{
    /// <summary>
    /// One-shot project bootstrapper. Builds the three UI scenes from scratch and wires
    /// every <c>[SerializeField]</c> reference programmatically, so the scenes are
    /// reproducible from source instead of hand-assembled in the editor.
    ///
    /// Run it from the menu (<b>Blackjack ▸ Build UI Scenes</b>) or headlessly:
    /// <code>
    /// Unity.exe -batchmode -projectPath "&lt;root&gt;" -logFile - \
    ///           -executeMethod BlackjackGame.EditorTools.SceneBootstrap.BuildAllFromCommandLine
    /// </code>
    /// It is idempotent: re-running overwrites the scenes and reuses existing config assets.
    /// </summary>
    public static class SceneBootstrap
    {
        // ---- Paths ----
        private const string ScenesFolder = "Assets/Scenes";
        private const string SettingsFolder = "Assets/Settings";
        private const string PrefabsFolder = "Assets/Prefabs";

        private const string MainMenuScenePath = ScenesFolder + "/MainMenu.unity";
        private const string GameScenePath = ScenesFolder + "/Game.unity";
        private const string StoreScenePath = ScenesFolder + "/Store.unity";

        private const string GameConfigPath = SettingsFolder + "/GameConfig.asset";
        private const string EconomyConfigPath = SettingsFolder + "/EconomyConfig.asset";
        private const string PackButtonPrefabPath = PrefabsFolder + "/PackButton.prefab";
        private const string CardPrefabPath = PrefabsFolder + "/CardView.prefab";
        private const string CardLibraryPath = SettingsFolder + "/CardSpriteLibrary.asset";

        // Art generated by art-source/generate_card_art.py
        private const string CardArtFolder = "Assets/Art/Cards";
        private const string FeltSpritePath = "Assets/Art/Table/Felt.png";

        // Gold UI kit generated by art-source/generate_ui_kit.py
        private const string UiArtFolder = "Assets/Art/UI";

        // Table plate + sprites lifted from the concept render by
        // art-source/extract_table_art.py
        private const string TableBackgroundPath = "Assets/Art/Table/TableBackground.png";

        // ---- Concept-render coordinate mapping -------------------------------
        // docs/screenshots/game-table.png is 1024x1536; the game canvas is 1080x1920 with
        // the render scaled to width and pinned 110px down (see extract_table_art.py).
        // Laying the scene out in the render's own pixel coordinates means every element
        // lands exactly where the concept art put it.
        private const float SrcScale = 1080f / 1024f;
        private const float SrcTopPad = 110f;

        private static float SrcX(float x) => x * SrcScale - 540f;
        private static float SrcY(float y) => 960f - (SrcTopPad + y * SrcScale);

        // ---- Palette ----
        private static readonly Color Felt = new Color(0.043f, 0.180f, 0.129f);
        private static readonly Color Panel = new Color(0.031f, 0.129f, 0.094f);
        /// <summary>Panels over the felt art — translucent so the table reads through.</summary>
        private static readonly Color GlassPanel = new Color(0.016f, 0.086f, 0.063f, 0.55f);
        private static readonly Color Gold = new Color(0.949f, 0.769f, 0.310f);
        private static readonly Color ButtonFill = new Color(0.129f, 0.353f, 0.263f);
        private static readonly Color ButtonAccent = new Color(0.729f, 0.180f, 0.180f);
        private static readonly Color Ink = new Color(0.918f, 0.945f, 0.933f);

        private static readonly Vector2 ReferenceResolution = new Vector2(1080f, 1920f);

        // =====================================================================
        //  Entry points
        // =====================================================================

        [MenuItem("Blackjack/Build UI Scenes", priority = 0)]
        public static void BuildUIScenes()
        {
            BuildAll();
            EditorUtility.DisplayDialog(
                "Blackjack",
                "MainMenu, Game and Store scenes were rebuilt, wired and added to Build Settings.",
                "Nice");
        }

        [MenuItem("Blackjack/Verify Scene Wiring", priority = 1)]
        public static void VerifySceneWiringMenu()
        {
            var problems = VerifyWiring();
            if (problems.Count == 0)
            {
                Debug.Log("[SceneBootstrap] Wiring OK — every serialized reference is assigned.");
                EditorUtility.DisplayDialog("Blackjack", "All scenes are fully wired.", "Good");
            }
            else
            {
                Debug.LogError("[SceneBootstrap] Wiring problems:\n - " + string.Join("\n - ", problems));
                EditorUtility.DisplayDialog("Blackjack", $"{problems.Count} wiring problem(s). See Console.", "OK");
            }
        }

        /// <summary>Batch-mode entry point. Exits non-zero if anything goes wrong.</summary>
        public static void BuildAllFromCommandLine()
        {
            try
            {
                BuildAll();

                var problems = VerifyWiring();
                if (problems.Count > 0)
                {
                    Debug.LogError("[SceneBootstrap] FAILED — unwired references:\n - " +
                                   string.Join("\n - ", problems));
                    EditorApplication.Exit(2);
                    return;
                }

                Debug.Log("[SceneBootstrap] SUCCESS — scenes built, wired and registered in Build Settings.");
                EditorApplication.Exit(0);
            }
            catch (Exception e)
            {
                Debug.LogError($"[SceneBootstrap] FAILED — {e}");
                EditorApplication.Exit(1);
            }
        }

        /// <summary>Batch-mode entry point that only checks wiring (no rebuild).</summary>
        public static void VerifyFromCommandLine()
        {
            try
            {
                var problems = VerifyWiring();
                if (problems.Count > 0)
                {
                    Debug.LogError("[SceneBootstrap] Wiring problems:\n - " + string.Join("\n - ", problems));
                    EditorApplication.Exit(2);
                    return;
                }
                Debug.Log("[SceneBootstrap] Wiring OK.");
                EditorApplication.Exit(0);
            }
            catch (Exception e)
            {
                Debug.LogError($"[SceneBootstrap] FAILED — {e}");
                EditorApplication.Exit(1);
            }
        }

        // =====================================================================
        //  Build pipeline
        // =====================================================================

        public static void BuildAll()
        {
            EnsureFolder(ScenesFolder);
            EnsureFolder(SettingsFolder);
            EnsureFolder(PrefabsFolder);

            DeleteObsoleteBakedLabels();

            // Text is TextMeshPro now, so the font assets and gold materials have to exist
            // before any scene is built. Cheap no-op once they're there.
            if (AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(FontAssetBuilder.DisplayAssetPath) == null)
                FontAssetBuilder.BuildAll();

            // Only guarantees the assets exist on disk. Do NOT hold the returned
            // references across a scene change — see RequireAsset below.
            EnsureAsset<GameConfig>(GameConfigPath);
            EnsureAsset<EconomyConfig>(EconomyConfigPath);
            EnsureAsset<CardSpriteLibrary>(CardLibraryPath);
            PopulateCardLibrary();
            CreateCardPrefab();

            BuildMainMenuScene();
            BuildGameScene();
            BuildStoreScene();

            RegisterBuildSettingsScenes();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        private static void BuildMainMenuScene()
        {
            Scene scene = NewScene();

            // Loaded AFTER NewScene(). Opening a new scene runs UnloadUnusedAssets, which
            // collects any asset held only by a plain C# local — a managed variable is not
            // a GC root as far as Unity's native object lifetime is concerned. Passing the
            // freshly-created ScriptableObjects in as arguments gives you a "fake null" here.
            GameConfig gameConfig = RequireAsset<GameConfig>(GameConfigPath);
            EconomyConfig economyConfig = RequireAsset<EconomyConfig>(EconomyConfigPath);

            // Composition root — persists across scene loads via MonoSingleton.
            var appManager = new GameObject("AppManager").AddComponent<AppManager>();
            Wire(appManager,
                ("_gameConfig", gameConfig),
                ("_economyConfig", economyConfig));

            Canvas canvas = CreateCanvas();
            Transform root = canvas.transform;
            CreateBackground(root, Color.white, UiSprite("felt_menu"));

            // ---- top bar: balance pill + quick-action circles -------------------
            CreateFrame(root, "BalancePill", "pill", new Vector2(-300f, 856f), new Vector2(400f, 104f));
            CreateSpriteImage(root, "CoinIcon", "icon_coin", new Vector2(-444f, 856f), 78f);
            CreateSpriteImage(root, "AddChipsIcon", "icon_plus", new Vector2(-154f, 856f), 46f);
            TMP_Text balanceLabel = CreateText(root, "BalanceLabel", "0",
                new Vector2(-294f, 856f), new Vector2(240f, 80f), 50f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);

            // Decorative for now — wired up when those screens exist.
            string[] quickIcons = { "icon_gift", "icon_settings", "icon_trophy" };
            for (int i = 0; i < quickIcons.Length; i++)
            {
                var at = new Vector2(214f + i * 128f, 856f);
                CreateSpriteImage(root, $"QuickButton{i}", "circle_button", at, 104f);
                CreateSpriteImage(root, $"QuickIcon{i}", quickIcons[i], at, 54f);
            }

            // ---- crest + wordmark ------------------------------------------------
            CreateSpriteImage(root, "Emblem", "emblem_ace", new Vector2(0f, 560f), 430f);
            CreateText(root, "Title", "BLACKJACK", new Vector2(0f, 276f),
                new Vector2(1000f, 220f), 146f, TextAlignmentOptions.Center,
                TextStyle.DisplayGold, characterSpacing: 2f);
            CreateSpriteImage(root, "TitleRule", "divider", new Vector2(0f, 188f), 40f);
            CreateText(root, "Tagline", "BEAT THE DEALER.  WIN BIG.", new Vector2(0f, 148f),
                new Vector2(960f, 60f), 36f, TextAlignmentOptions.Center,
                TextStyle.BodyGold, characterSpacing: 8f);

            // ---- action rows -----------------------------------------------------
            Button playButton = CreateMenuRow(root, "PlayButton", "btn_green", "icon_cards",
                "PLAY", "DEAL YOUR LUCK", new Vector2(0f, -28f));
            Button storeButton = CreateMenuRow(root, "StoreButton", "btn_blue", "icon_cart",
                "STORE", "GET CHIPS & ITEMS", new Vector2(0f, -238f));
            Button rewardsButton = CreateMenuRow(root, "RewardsButton", "btn_red", "icon_gift",
                "DAILY REWARDS", "CLAIM YOUR PRIZE", new Vector2(0f, -448f));

            TMP_Text rewardStatusLabel = CreateText(root, "RewardStatusLabel", "",
                new Vector2(0f, -580f), new Vector2(940f, 70f), 34f,
                TextAlignmentOptions.Center, TextStyle.BodyInk);

            // ---- house rules ------------------------------------------------------
            CreateSpriteImage(root, "RulesRuleTop", "divider", new Vector2(0f, -640f), 36f);
            CreateText(root, "Rule1", "BLACKJACK PAYS 3 TO 2", new Vector2(0f, -700f),
                new Vector2(960f, 60f), 46f, TextAlignmentOptions.Center,
                TextStyle.DisplayGold, characterSpacing: 4f);
            CreateText(root, "Rule2", "DEALER MUST HIT SOFT 17", new Vector2(0f, -756f),
                new Vector2(960f, 50f), 30f, TextAlignmentOptions.Center,
                TextStyle.BodyGold, characterSpacing: 6f);
            CreateSpriteImage(root, "RulesRuleBottom", "divider", new Vector2(0f, -812f), 36f);

            TMP_Text disclaimer = CreateText(root, "Disclaimer",
                "Virtual chips only. No real money, no cash prizes.",
                new Vector2(0f, -886f), new Vector2(960f, 60f), 26f,
                TextAlignmentOptions.Center, TextStyle.BodyInk);
            disclaimer.alpha = 0.5f;

            var ui = canvas.gameObject.AddComponent<MainMenuUI>();
            Wire(ui,
                ("_playButton", playButton),
                ("_storeButton", storeButton),
                ("_rewardsButton", rewardsButton),
                ("_balanceLabel", balanceLabel),
                ("_rewardStatusLabel", rewardStatusLabel));

            SaveScene(scene, MainMenuScenePath);
        }

        private static void BuildGameScene()
        {
            Scene scene = NewScene();

            new GameObject("GameManager").AddComponent<GameManager>();

            Canvas canvas = CreateCanvas();
            Transform root = canvas.transform;

            // The whole table — rail, chip tray, shoe, felt, arc text, spade medallion —
            // is the concept render itself with the dynamic bits inpainted out. Positions
            // below are the render's own, mapped through SrcX/SrcY.
            CreateBackground(root, Color.white, LoadSprite(TableBackgroundPath));

            // --- top bar ---------------------------------------------------------
            // Back arrow, then the balance pill — the same arrangement the store render
            // uses. The pill is nudged right of the render's position so the two don't
            // collide: at the render's x they overlapped by ~50px.
            Button backButton = CreateCircleButton(root, "BackButton", "icon_back",
                new Vector2(SrcX(62), SrcY(70)), 100f);

            CreateFrame(root, "BalancePill", "pill",
                new Vector2(SrcX(300), SrcY(70)), new Vector2(360f, 96f));
            CreateSpriteImage(root, "CoinIcon", "icon_coin", new Vector2(SrcX(154), SrcY(70)), 72f);
            CreateSpriteImage(root, "AddChipsIcon", "icon_plus", new Vector2(SrcX(446), SrcY(70)), 42f);
            TMP_Text balanceLabel = CreateText(root, "BalanceLabel", "0",
                new Vector2(SrcX(304), SrcY(70)), new Vector2(200f, 72f), 46f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);

            CreateCircleButton(root, "QuickGift", "icon_gift", new Vector2(SrcX(722), SrcY(70)), 100f);
            CreateCircleButton(root, "QuickSettings", "icon_settings", new Vector2(SrcX(830), SrcY(70)), 100f);
            CreateCircleButton(root, "QuickTrophy", "icon_trophy", new Vector2(SrcX(938), SrcY(70)), 100f);

            // --- dealer ----------------------------------------------------------
            HandView dealerHandView = CreateHandView(root, "DealerHandView",
                new Vector2(SrcX(516), SrcY(300)), new Vector2(172f, 241f));
            TMP_Text dealerHandLabel = CreateText(root, "DealerHandLabel", "Dealer",
                new Vector2(SrcX(512), SrcY(150)), new Vector2(700f, 60f), 40f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);

            // --- player ----------------------------------------------------------
            HandView playerHandView = CreateHandView(root, "PlayerHandView",
                new Vector2(SrcX(470), SrcY(828)), new Vector2(206f, 288f));
            TMP_Text playerHandLabel = CreateText(root, "PlayerHandLabel", "Place your bet",
                new Vector2(SrcX(512), SrcY(636)), new Vector2(820f, 60f), 40f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);

            CreateSpriteImage(root, "BetChip", "chip_stack", new Vector2(SrcX(750), SrcY(884)), 150f);

            TMP_Text outcomeLabel = CreateText(root, "OutcomeLabel", "",
                new Vector2(SrcX(512), SrcY(1046)), new Vector2(1000f, 90f), 56f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);

            // --- control band: bet row and action row share the same strip ---------
            float bandY = SrcY(1179);
            var buttonSize = new Vector2(212f, 172f);
            float[] slots = { SrcX(147), SrcX(384), SrcX(624), SrcX(866) };

            CanvasGroup betRow = CreateRow(root, "BetRow");
            TMP_InputField betInput = CreateInputField(betRow.transform, "BetInput", "100",
                new Vector2(SrcX(300), bandY), new Vector2(400f, 140f));
            Button dealButton = CreateActionButton(betRow.transform, "DealButton", null, "DEAL",
                new Vector2(SrcX(720), bandY), new Vector2(440f, 150f));

            CanvasGroup actionRow = CreateRow(root, "ActionRow");
            Button hitButton = CreateActionButton(actionRow.transform, "HitButton", "icon_hit", "HIT",
                new Vector2(slots[0], bandY), buttonSize);
            Button standButton = CreateActionButton(actionRow.transform, "StandButton", "icon_stand", "STAND",
                new Vector2(slots[1], bandY), buttonSize);
            Button doubleButton = CreateActionButton(actionRow.transform, "DoubleButton", "icon_double", "DOUBLE",
                new Vector2(slots[2], bandY), buttonSize);
            Button splitButton = CreateActionButton(actionRow.transform, "SplitButton", "icon_split", "SPLIT",
                new Vector2(slots[3], bandY), buttonSize);

            var ui = canvas.gameObject.AddComponent<GameTableUI>();
            Wire(ui,
                ("_betInput", betInput),
                ("_dealButton", dealButton),
                ("_betRow", betRow),
                ("_actionRow", actionRow),
                ("_hitButton", hitButton),
                ("_standButton", standButton),
                ("_doubleButton", doubleButton),
                ("_splitButton", splitButton),
                ("_dealerHandView", dealerHandView),
                ("_playerHandView", playerHandView),
                ("_dealerHandLabel", dealerHandLabel),
                ("_playerHandLabel", playerHandLabel),
                ("_outcomeLabel", outcomeLabel),
                ("_balanceLabel", balanceLabel),
                ("_backButton", backButton));

            SaveScene(scene, GameScenePath);
        }

        private static void BuildStoreScene()
        {
            Scene scene = NewScene();

            // Built inside the fresh scene so the temporary instance never dirties another one,
            // then re-loaded from disk so we hold a reference the asset pipeline knows about.
            CreatePackButtonPrefab();
            var prefabGo = AssetDatabase.LoadAssetAtPath<GameObject>(PackButtonPrefabPath);
            if (prefabGo == null)
                throw new InvalidOperationException($"Could not load prefab at {PackButtonPrefabPath}");
            Button packButtonPrefab = prefabGo.GetComponent<Button>();

            Canvas canvas = CreateCanvas();
            CreateBackground(canvas.transform, Color.white, LoadSprite(FeltSpritePath));

            CreateText(canvas.transform, "Title", "GET CHIPS",
                new Vector2(0f, 780f), new Vector2(1000f, 150f), 108f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold, characterSpacing: 4f);
            TMP_Text balanceLabel = CreateText(canvas.transform, "BalanceLabel", "Balance: 0",
                new Vector2(0f, 660f), new Vector2(1000f, 80f), 46f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);

            // Pack rows are instantiated into this container at runtime by StoreUI.
            CreatePanel(canvas.transform, "PackPanel", new Vector2(0f, 40f), new Vector2(1000f, 1080f));
            GameObject listGo = NewUIObject("PackList", canvas.transform);
            Place(listGo, new Vector2(0f, 40f), new Vector2(940f, 1040f));
            var layout = listGo.AddComponent<VerticalLayoutGroup>();
            layout.spacing = 24f;
            layout.padding = new RectOffset(10, 10, 20, 20);
            layout.childAlignment = TextAnchor.UpperCenter;
            layout.childForceExpandWidth = true;
            layout.childForceExpandHeight = false;
            layout.childControlWidth = true;
            layout.childControlHeight = false;

            TMP_Text statusLabel = CreateText(canvas.transform, "StatusLabel", "",
                new Vector2(0f, -600f), new Vector2(1000f, 110f), 40f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);

            Button backButton = CreateButton(canvas.transform, "BackButton", "BACK",
                new Vector2(0f, -760f), new Vector2(440f, 130f), Panel);

            TMP_Text storeDisclaimer = CreateText(canvas.transform, "Disclaimer",
                "Chips are virtual and have no cash value.",
                new Vector2(0f, -880f), new Vector2(1000f, 60f), 26f,
                TextAlignmentOptions.Center, TextStyle.BodyInk);
            storeDisclaimer.alpha = 0.5f;

            var ui = canvas.gameObject.AddComponent<StoreUI>();
            Wire(ui,
                ("_packListRoot", listGo.transform),
                ("_packButtonPrefab", packButtonPrefab),
                ("_balanceLabel", balanceLabel),
                ("_statusLabel", statusLabel),
                ("_backButton", backButton));

            SaveScene(scene, StoreScenePath);
        }

        private static void RegisterBuildSettingsScenes()
        {
            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(MainMenuScenePath, true),
                new EditorBuildSettingsScene(GameScenePath, true),
                new EditorBuildSettingsScene(StoreScenePath, true),
            };
            Debug.Log("[SceneBootstrap] Build Settings: MainMenu, Game, Store.");
        }

        // =====================================================================
        //  Verification
        // =====================================================================

        /// <summary>
        /// Opens each scene and reports any serialized object reference that was left null,
        /// plus any missing scene/build-settings entry. Empty list == fully wired.
        /// </summary>
        public static List<string> VerifyWiring()
        {
            var problems = new List<string>();

            CheckScene(MainMenuScenePath, problems, typeof(AppManager), typeof(MainMenuUI));
            CheckScene(GameScenePath, problems, typeof(GameManager), typeof(GameTableUI), typeof(HandView));
            CheckScene(StoreScenePath, problems, typeof(StoreUI));

            // The card faces live in an array, which the per-field scan below cannot see.
            var library = AssetDatabase.LoadAssetAtPath<CardSpriteLibrary>(CardLibraryPath);
            if (library == null) problems.Add($"Missing CardSpriteLibrary at {CardLibraryPath}.");
            else if (!library.IsComplete)
                problems.Add("CardSpriteLibrary is incomplete — some faces or the back are unassigned.");

            if (AssetDatabase.LoadAssetAtPath<GameObject>(CardPrefabPath) == null)
                problems.Add($"Missing card prefab at {CardPrefabPath}.");
            if (AssetDatabase.LoadAssetAtPath<Sprite>(FeltSpritePath) == null)
                problems.Add($"Missing table felt sprite at {FeltSpritePath}.");

            foreach (string path in new[]
                     {
                         FontAssetBuilder.DisplayAssetPath, FontAssetBuilder.BodyBoldAssetPath,
                         FontAssetBuilder.BodyAssetPath, FontAssetBuilder.GoldMaterialPath,
                         FontAssetBuilder.GoldSmallMaterialPath, FontAssetBuilder.InkMaterialPath,
                         FontAssetBuilder.GoldGradientPath,
                     })
            {
                if (AssetDatabase.LoadAssetAtPath<Object>(path) == null)
                    problems.Add($"Missing font asset '{path}' — run Blackjack ▸ Rebuild Font Assets.");
            }

            string[] expected = { MainMenuScenePath, GameScenePath, StoreScenePath };
            EditorBuildSettingsScene[] registered = EditorBuildSettings.scenes;
            for (int i = 0; i < expected.Length; i++)
            {
                if (i >= registered.Length || registered[i].path != expected[i] || !registered[i].enabled)
                {
                    problems.Add($"Build Settings slot {i} should be an enabled '{expected[i]}'.");
                }
            }

            return problems;
        }

        private static void CheckScene(string scenePath, List<string> problems, params Type[] requiredComponents)
        {
            if (AssetDatabase.LoadAssetAtPath<SceneAsset>(scenePath) == null)
            {
                problems.Add($"Scene missing: {scenePath}");
                return;
            }

            Scene scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);

            foreach (Type type in requiredComponents)
            {
                var found = Object.FindObjectsByType(type, FindObjectsSortMode.None);
                if (found.Length == 0)
                {
                    problems.Add($"{scene.name}: no {type.Name} in the scene.");
                    continue;
                }

                foreach (Object o in found)
                {
                    if (o is Component component) CollectUnassignedFields(component, scene.name, problems);
                }
            }

            if (Object.FindFirstObjectByType<EventSystem>() == null)
                problems.Add($"{scene.name}: no EventSystem (UI would be unclickable).");
            if (Object.FindFirstObjectByType<Canvas>() == null)
                problems.Add($"{scene.name}: no Canvas.");
        }

        private static void CollectUnassignedFields(Component component, string sceneName, List<string> problems)
        {
            var so = new SerializedObject(component);
            SerializedProperty it = so.GetIterator();
            bool enterChildren = true;
            while (it.NextVisible(enterChildren))
            {
                enterChildren = false;
                if (it.propertyType != SerializedPropertyType.ObjectReference) continue;
                if (it.objectReferenceValue == null)
                    problems.Add($"{sceneName}: {component.GetType().Name}.{it.propertyPath} is not assigned.");
            }
        }

        // =====================================================================
        //  Asset / scene helpers
        // =====================================================================

        private static Scene NewScene()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var cameraGo = new GameObject("Main Camera", typeof(Camera));
            cameraGo.tag = "MainCamera";
            cameraGo.transform.position = new Vector3(0f, 0f, -10f);
            Camera camera = cameraGo.GetComponent<Camera>();
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = Felt;
            camera.orthographic = true;

            new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));

            return scene;
        }

        private static void SaveScene(Scene scene, string path)
        {
            if (!EditorSceneManager.SaveScene(scene, path))
                throw new InvalidOperationException($"Could not save scene to {path}");
            Debug.Log($"[SceneBootstrap] Built {path}");
        }

        /// <summary>
        /// Loads an asset that must already exist. Call this immediately before use rather
        /// than caching the reference across a scene load — see the note in BuildMainMenuScene.
        /// </summary>
        private static T RequireAsset<T>(string path) where T : ScriptableObject
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset == null)
                throw new InvalidOperationException(
                    $"Expected a {typeof(T).Name} at '{path}' but could not load it.");
            return asset;
        }

        private static T EnsureAsset<T>(string path) where T : ScriptableObject
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset != null) return asset;

            asset = ScriptableObject.CreateInstance<T>();
            AssetDatabase.CreateAsset(asset, path);
            AssetDatabase.SaveAssets();
            Debug.Log($"[SceneBootstrap] Created {typeof(T).Name} at {path}");
            return asset;
        }

        private static void EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return;

            string parent = Path.GetDirectoryName(folder)?.Replace('\\', '/');
            string leaf = Path.GetFileName(folder);
            if (string.IsNullOrEmpty(parent) || string.IsNullOrEmpty(leaf)) return;

            EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, leaf);
        }

        /// <summary>Assigns private [SerializeField] references without needing public setters.</summary>
        private static void Wire(Component target, params (string field, Object value)[] bindings)
        {
            var so = new SerializedObject(target);
            foreach ((string field, Object value) in bindings)
            {
                SerializedProperty prop = so.FindProperty(field);
                if (prop == null)
                    throw new InvalidOperationException(
                        $"{target.GetType().Name} has no serialized field named '{field}'. " +
                        "Did the script change?");
                if (value == null)
                    throw new InvalidOperationException(
                        $"{target.GetType().Name}.{field}: nothing to assign (value was null).");

                prop.objectReferenceValue = value;
            }
            so.ApplyModifiedPropertiesWithoutUndo();
        }

        // =====================================================================
        //  UI construction helpers
        // =====================================================================

        private static GameObject NewUIObject(string name, Transform parent)
        {
            var go = new GameObject(name, typeof(RectTransform));
            go.transform.SetParent(parent, false);
            return go;
        }

        private static RectTransform Place(GameObject go, Vector2 position, Vector2 size)
        {
            var rt = (RectTransform)go.transform;
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = position;
            rt.sizeDelta = size;
            return rt;
        }

        private static RectTransform Stretch(GameObject go, float padding = 0f)
        {
            var rt = (RectTransform)go.transform;
            rt.anchorMin = Vector2.zero;
            rt.anchorMax = Vector2.one;
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.offsetMin = new Vector2(padding, padding);
            rt.offsetMax = new Vector2(-padding, -padding);
            return rt;
        }

        private static Canvas CreateCanvas()
        {
            var go = new GameObject("Canvas", typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster));
            var canvas = go.GetComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            var scaler = go.GetComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = ReferenceResolution;
            scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
            scaler.matchWidthOrHeight = 0.5f;

            return canvas;
        }

        private static Sprite LoadSprite(string path)
        {
            var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path);
            if (sprite == null)
                Debug.LogWarning($"[SceneBootstrap] No sprite at '{path}'. " +
                                 "Run art-source/generate_card_art.py, then reimport.");
            return sprite;
        }

        // ---- gold UI kit helpers -------------------------------------------

        /// <summary>
        /// Removes the label/title sprites that used to carry the gold text. They were
        /// replaced by live TextMeshPro, which is sharp at any size and can't be scaled
        /// wrong — the old sprites shipped their glyphs inside ~26px of transparent
        /// padding, so sizing by sprite height silently shrank the text.
        /// Goes through AssetDatabase so the .meta files go with them.
        /// </summary>
        private static void DeleteObsoleteBakedLabels()
        {
            if (!AssetDatabase.IsValidFolder(UiArtFolder)) return;

            int removed = 0;
            foreach (string guid in AssetDatabase.FindAssets("t:Texture2D", new[] { UiArtFolder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                string file = Path.GetFileName(path);
                if (file.StartsWith("label_", StringComparison.Ordinal) ||
                    file.StartsWith("title_", StringComparison.Ordinal))
                {
                    if (AssetDatabase.DeleteAsset(path)) removed++;
                }
            }

            // chip_stack was first written to Assets/Art/Table; it belongs with the kit.
            if (AssetDatabase.DeleteAsset("Assets/Art/Table/chip_stack.png")) removed++;

            if (removed > 0)
                Debug.Log($"[SceneBootstrap] Removed {removed} obsolete sprite(s).");
        }

        /// <summary>Loads a kit sprite by bare name; ".b&lt;N&gt;" nine-slice files resolve too.</summary>
        private static Sprite UiSprite(string name)
        {
            var sprite = AssetDatabase.LoadAssetAtPath<Sprite>($"{UiArtFolder}/{name}.png");
            if (sprite != null) return sprite;

            // Try the nine-sliced variants, whose filenames carry a border suffix.
            foreach (string guid in AssetDatabase.FindAssets($"{name} t:Sprite", new[] { UiArtFolder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (Path.GetFileName(path).StartsWith(name + ".b", StringComparison.Ordinal))
                    return AssetDatabase.LoadAssetAtPath<Sprite>(path);
            }

            throw new InvalidOperationException(
                $"UI sprite '{name}' not found in {UiArtFolder}. " +
                "Run 'python3 art-source/generate_ui_kit.py' from the project root.");
        }

        /// <summary>A nine-sliced frame (button background, pill, panel).</summary>
        private static Image CreateFrame(Transform parent, string name, string sprite,
            Vector2 position, Vector2 size)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);
            var image = go.AddComponent<Image>();
            image.sprite = UiSprite(sprite);
            image.type = Image.Type.Sliced;
            image.pixelsPerUnitMultiplier = 1f;
            image.raycastTarget = false;
            return image;
        }

        /// <summary>
        /// An icon or baked-label sprite. Give it a target height, or pass
        /// <paramref name="widthOverride"/> to size by width instead — the other
        /// dimension follows the sprite's aspect either way.
        /// </summary>
        private static Image CreateSpriteImage(Transform parent, string name, string sprite,
            Vector2 position, float height, float widthOverride = 0f)
        {
            Sprite s = UiSprite(sprite);
            float aspect = s.rect.width / s.rect.height;

            float width;
            if (widthOverride > 0f)
            {
                width = widthOverride;
                height = width / aspect;
            }
            else
            {
                width = height * aspect;
            }

            GameObject go = NewUIObject(name, parent);
            Place(go, position, new Vector2(width, height));
            var image = go.AddComponent<Image>();
            image.sprite = s;
            image.type = Image.Type.Simple;
            image.preserveAspect = true;
            image.raycastTarget = false;
            return image;
        }

        /// <summary>A button whose background is a nine-sliced gold frame.</summary>
        private static Button CreateFrameButton(Transform parent, string name, string sprite,
            Vector2 position, Vector2 size)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var image = go.AddComponent<Image>();
            image.sprite = UiSprite(sprite);
            image.type = Image.Type.Sliced;
            image.pixelsPerUnitMultiplier = 1f;

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            ColorBlock colors = button.colors;
            colors.normalColor = Color.white;
            colors.highlightedColor = new Color(1.10f, 1.10f, 1.10f, 1f);
            colors.pressedColor = new Color(0.80f, 0.80f, 0.80f, 1f);
            // Distinctly dimmer + desaturated so unavailable actions read at a glance.
            colors.disabledColor = new Color(0.42f, 0.44f, 0.42f, 0.75f);
            colors.fadeDuration = 0.08f;
            button.colors = colors;

            return button;
        }

        /// <summary>A full-canvas container with a CanvasGroup, used to swap control rows.</summary>
        private static CanvasGroup CreateRow(Transform parent, string name)
        {
            GameObject go = NewUIObject(name, parent);
            Stretch(go);
            return go.AddComponent<CanvasGroup>();
        }

        /// <summary>Round gold button from the kit, with a centred icon.</summary>
        private static Button CreateCircleButton(Transform parent, string name, string icon,
            Vector2 position, float diameter)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, new Vector2(diameter, diameter));

            var image = go.AddComponent<Image>();
            image.sprite = UiSprite("circle_button");
            image.type = Image.Type.Simple;

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            CreateSpriteImage(go.transform, "Icon", icon, Vector2.zero, diameter * 0.52f);
            return button;
        }

        /// <summary>
        /// Table action button using the frame lifted from the concept render, with the
        /// render's own icon above a TMP label — matching the mockup's HIT/STAND/DOUBLE/SPLIT.
        /// </summary>
        private static Button CreateActionButton(Transform parent, string name, string icon,
            string label, Vector2 position, Vector2 size)
        {
            Button button = CreateFrameButton(parent, name, "btn_action", position, size);
            Transform t = button.transform;

            if (!string.IsNullOrEmpty(icon))
            {
                CreateSpriteImage(t, "Icon", icon, new Vector2(0f, size.y * 0.13f), size.y * 0.42f);
                CreateText(t, "Label", label, new Vector2(0f, -size.y * 0.30f),
                    new Vector2(size.x - 20f, size.y * 0.30f), size.y * 0.20f,
                    TextAlignmentOptions.Center, TextStyle.DisplayGold, characterSpacing: 3f);
            }
            else
            {
                CreateText(t, "Label", label, Vector2.zero,
                    new Vector2(size.x - 20f, size.y * 0.5f), size.y * 0.30f,
                    TextAlignmentOptions.Center, TextStyle.DisplayGold, characterSpacing: 4f);
            }

            return button;
        }

        /// <summary>One main-menu row: gold frame, icon, TMP title + subtitle, chevron.</summary>
        private static Button CreateMenuRow(Transform parent, string name, string frame,
            string icon, string label, string subLabel, Vector2 position)
        {
            var size = new Vector2(888f, 176f);
            Button button = CreateFrameButton(parent, name, frame, position, size);
            Transform t = button.transform;

            CreateSpriteImage(t, "Icon", icon, new Vector2(-size.x / 2f + 96f, 0f), 76f);
            CreateSpriteImage(t, "Chevron", "icon_chevron", new Vector2(size.x / 2f - 78f, 0f), 54f);

            CreateText(t, "Label", label, new Vector2(20f, 24f), new Vector2(size.x - 220f, 74f),
                58f, TextAlignmentOptions.Center, TextStyle.DisplayGold, characterSpacing: 4f);
            CreateText(t, "SubLabel", subLabel, new Vector2(20f, -34f),
                new Vector2(size.x - 220f, 44f), 30f, TextAlignmentOptions.Center,
                TextStyle.BodyInk, characterSpacing: 4f);

            return button;
        }

        private static Image CreateBackground(Transform parent, Color color, Sprite sprite = null)
        {
            GameObject go = NewUIObject("Background", parent);
            Stretch(go);
            var image = go.AddComponent<Image>();
            image.color = color;
            image.raycastTarget = false;
            if (sprite != null)
            {
                image.sprite = sprite;
                image.type = Image.Type.Simple;
                image.preserveAspect = false;
            }
            return image;
        }

        /// <summary>
        /// A HandView plus the child transform its cards are parented to. Splitting the
        /// two keeps the layout anchor independent of the component's own transform.
        /// </summary>
        private static HandView CreateHandView(Transform parent, string name, Vector2 position,
            Vector2? cardSize = null)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, new Vector2(960f, 260f));

            GameObject rootGo = NewUIObject("Cards", go.transform);
            Place(rootGo, Vector2.zero, Vector2.zero);

            var view = go.AddComponent<HandView>();
            var prefabGo = AssetDatabase.LoadAssetAtPath<GameObject>(CardPrefabPath);
            if (prefabGo == null)
                throw new InvalidOperationException($"Card prefab missing at {CardPrefabPath}");

            Wire(view,
                ("_library", RequireAsset<CardSpriteLibrary>(CardLibraryPath)),
                ("_cardPrefab", prefabGo.GetComponent<Image>()),
                ("_cardRoot", rootGo.GetComponent<RectTransform>()),
                ("_shadowSprite", UiSprite("card_shadow")));

            if (cardSize.HasValue)
            {
                var so = new SerializedObject(view);
                so.FindProperty("_cardSize").vector2Value = cardSize.Value;
                so.ApplyModifiedPropertiesWithoutUndo();
            }

            return view;
        }

        private static Image CreatePanel(Transform parent, string name, Vector2 position, Vector2 size,
            Color? color = null)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);
            var image = go.AddComponent<Image>();
            image.color = color ?? Panel;
            image.raycastTarget = false;
            return image;
        }

        /// <summary>
        /// The three text treatments in the game. Baked label sprites used to do this job;
        /// TMP does it live, stays sharp at any size, and can't get its scale wrong.
        /// </summary>
        public enum TextStyle
        {
            /// <summary>Serif display face, metallic gold, bevelled — titles and button labels.</summary>
            DisplayGold,
            /// <summary>Bold body face in gold — subtitles, house rules.</summary>
            BodyGold,
            /// <summary>Plain body face in warm off-white — status lines, disclaimers.</summary>
            BodyInk,
        }

        private static T RequireFontAsset<T>(string path) where T : Object
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset == null)
                throw new InvalidOperationException(
                    $"Missing '{path}'. Run Blackjack ▸ Rebuild Font Assets first.");
            return asset;
        }

        private static TMP_Text CreateText(
            Transform parent,
            string name,
            string content,
            Vector2 position,
            Vector2 size,
            float fontSize,
            TextAlignmentOptions alignment = TextAlignmentOptions.Center,
            TextStyle style = TextStyle.BodyInk,
            float characterSpacing = 0f,
            bool wrap = false)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var text = go.AddComponent<TextMeshProUGUI>();
            text.text = content;
            text.fontSize = fontSize;
            text.alignment = alignment;
            text.characterSpacing = characterSpacing;
            text.raycastTarget = false;
            text.textWrappingMode = wrap ? TextWrappingModes.Normal : TextWrappingModes.NoWrap;
            text.overflowMode = TextOverflowModes.Overflow;

            switch (style)
            {
                case TextStyle.DisplayGold:
                    text.font = RequireFontAsset<TMP_FontAsset>(FontAssetBuilder.DisplayAssetPath);
                    text.fontSharedMaterial = RequireFontAsset<Material>(FontAssetBuilder.GoldMaterialPath);
                    text.colorGradientPreset =
                        RequireFontAsset<TMP_ColorGradient>(FontAssetBuilder.GoldGradientPath);
                    text.enableVertexGradient = true;
                    break;

                case TextStyle.BodyGold:
                    text.font = RequireFontAsset<TMP_FontAsset>(FontAssetBuilder.BodyBoldAssetPath);
                    text.fontSharedMaterial = RequireFontAsset<Material>(FontAssetBuilder.GoldSmallMaterialPath);
                    text.colorGradientPreset =
                        RequireFontAsset<TMP_ColorGradient>(FontAssetBuilder.GoldGradientPath);
                    text.enableVertexGradient = true;
                    break;

                default:
                    text.font = RequireFontAsset<TMP_FontAsset>(FontAssetBuilder.BodyAssetPath);
                    text.fontSharedMaterial = RequireFontAsset<Material>(FontAssetBuilder.InkMaterialPath);
                    break;
            }

            return text;
        }

        private static Button CreateButton(
            Transform parent,
            string name,
            string label,
            Vector2 position,
            Vector2 size,
            Color fill)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var image = go.AddComponent<Image>();
            image.color = fill;

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            ColorBlock colors = button.colors;
            colors.highlightedColor = Color.Lerp(fill, Color.white, 0.15f);
            colors.pressedColor = Color.Lerp(fill, Color.black, 0.2f);
            colors.disabledColor = new Color(fill.r, fill.g, fill.b, 0.35f);
            button.colors = colors;

            CreateText(go.transform, "Label", label, Vector2.zero,
                new Vector2(size.x - 16f, size.y - 16f),
                Mathf.Min(size.y * 0.34f, 52f), TextAlignmentOptions.Center,
                TextStyle.DisplayGold, characterSpacing: 2f);

            return button;
        }

        private static TMP_InputField CreateInputField(
            Transform parent,
            string name,
            string defaultValue,
            Vector2 position,
            Vector2 size)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var background = go.AddComponent<Image>();
            background.sprite = UiSprite("pill");
            background.type = Image.Type.Sliced;
            background.pixelsPerUnitMultiplier = 1f;

            var input = go.AddComponent<TMP_InputField>();
            input.targetGraphic = background;
            input.contentType = TMP_InputField.ContentType.IntegerNumber;
            input.characterLimit = 9;

            // TMP_InputField needs its text area to be a child RectTransform with a mask,
            // otherwise the caret and text render outside the field.
            GameObject viewport = NewUIObject("Text Area", go.transform);
            Stretch(viewport, 22f);
            viewport.AddComponent<RectMask2D>();

            TMP_Text placeholder = CreateText(viewport.transform, "Placeholder", "Bet…",
                Vector2.zero, size - new Vector2(44f, 44f), 44f,
                TextAlignmentOptions.Center, TextStyle.BodyInk);
            placeholder.fontStyle = FontStyles.Italic;
            placeholder.color = new Color(0.78f, 0.76f, 0.68f, 0.7f);
            Stretch(placeholder.gameObject);

            TMP_Text text = CreateText(viewport.transform, "Text", string.Empty,
                Vector2.zero, size - new Vector2(44f, 44f), 48f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);
            text.richText = false;
            Stretch(text.gameObject);

            input.textViewport = (RectTransform)viewport.transform;
            input.textComponent = text;
            input.placeholder = placeholder;
            input.text = defaultValue;

            return input;
        }

        /// <summary>
        /// Fills the CardSpriteLibrary asset from Assets/Art/Cards. File names encode the
        /// suit and rank so the mapping is mechanical: card_&lt;Suit&gt;_&lt;01..13&gt;.png,
        /// with Suit spelled exactly as the C# enum.
        /// </summary>
        private static void PopulateCardLibrary()
        {
            CardSpriteLibrary library = RequireAsset<CardSpriteLibrary>(CardLibraryPath);
            var so = new SerializedObject(library);

            SerializedProperty faces = so.FindProperty("_faces");
            faces.arraySize = CardSpriteLibrary.FaceCount;

            var missing = new List<string>();
            foreach (Suit suit in (Suit[])Enum.GetValues(typeof(Suit)))
            {
                for (int rank = 1; rank <= 13; rank++)
                {
                    string path = $"{CardArtFolder}/card_{suit}_{rank:00}.png";
                    var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path);
                    if (sprite == null) missing.Add(path);

                    int index = CardSpriteLibrary.IndexOf(new Card(suit, (Rank)rank));
                    faces.GetArrayElementAtIndex(index).objectReferenceValue = sprite;
                }
            }

            var back = AssetDatabase.LoadAssetAtPath<Sprite>($"{CardArtFolder}/card_Back.png");
            if (back == null) missing.Add($"{CardArtFolder}/card_Back.png");
            so.FindProperty("_back").objectReferenceValue = back;

            so.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(library);

            if (missing.Count > 0)
            {
                throw new InvalidOperationException(
                    $"{missing.Count} card sprite(s) missing, first: {missing[0]}. " +
                    "Run 'python3 art-source/generate_card_art.py' from the project root. " +
                    "If the PNGs exist, they may have imported as Textures rather than " +
                    "Sprites — ArtImportSettings should prevent that.");
            }

            Debug.Log($"[SceneBootstrap] Card library populated ({CardSpriteLibrary.FaceCount} faces + back).");
        }

        /// <summary>The card template HandView clones. A plain Image, sized at runtime.</summary>
        private static void CreateCardPrefab()
        {
            EnsureFolder(PrefabsFolder);

            GameObject go = NewUIObject("CardView", null);
            Place(go, Vector2.zero, new Vector2(150f, 210f));
            var image = go.AddComponent<Image>();
            image.preserveAspect = true;
            image.raycastTarget = false;
            image.sprite = LoadSprite($"{CardArtFolder}/card_Back.png");

            GameObject saved = PrefabUtility.SaveAsPrefabAsset(go, CardPrefabPath);
            Object.DestroyImmediate(go);

            if (saved == null)
                throw new InvalidOperationException($"Could not save prefab to {CardPrefabPath}");

            Debug.Log($"[SceneBootstrap] Built {CardPrefabPath}");
        }

        /// <summary>
        /// Builds (or rebuilds) the row template StoreUI clones for each chip pack.
        /// A Button with a stretched child Text, which is exactly what StoreUI expects.
        /// </summary>
        private static Button CreatePackButtonPrefab()
        {
            EnsureFolder(PrefabsFolder);

            Button temp = CreateButton(null, "PackButton", "Chip Pack",
                Vector2.zero, new Vector2(900f, 150f), ButtonFill);

            var layoutElement = temp.gameObject.AddComponent<LayoutElement>();
            layoutElement.preferredHeight = 150f;
            layoutElement.minHeight = 150f;
            layoutElement.preferredWidth = 900f;

            GameObject saved = PrefabUtility.SaveAsPrefabAsset(temp.gameObject, PackButtonPrefabPath);
            Object.DestroyImmediate(temp.gameObject);

            if (saved == null)
                throw new InvalidOperationException($"Could not save prefab to {PackButtonPrefabPath}");

            Debug.Log($"[SceneBootstrap] Built {PackButtonPrefabPath}");
            return saved.GetComponent<Button>();
        }

        /// <summary>Human-readable dump of the current wiring — handy when debugging by hand.</summary>
        [MenuItem("Blackjack/Log Scene Wiring Report", priority = 20)]
        private static void LogReport()
        {
            var sb = new StringBuilder("[SceneBootstrap] Wiring report\n");
            List<string> problems = VerifyWiring();
            sb.AppendLine(problems.Count == 0
                ? "All serialized references assigned."
                : string.Join("\n", problems));
            sb.AppendLine("Build Settings:");
            foreach (EditorBuildSettingsScene s in EditorBuildSettings.scenes)
                sb.AppendLine($"  [{(s.enabled ? "x" : " ")}] {s.path}");
            Debug.Log(sb.ToString());
        }
    }
}
