using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using BlackjackGame.Config;
using BlackjackGame.Blackjack.Cards;
using BlackjackGame.Core;
using BlackjackGame.UI.Components;
using BlackjackGame.UI.Screens;
using TMPro;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using Object = UnityEngine.Object;

namespace BlackjackGame.EditorTools
{
    /// <summary>
    /// One-shot project bootstrapper. Builds the three UI scenes from scratch and wires
    /// every <c>[SerializeField]</c> reference programmatically, so the scenes are
    /// reproducible from source instead of hand-assembled in the editor.
    ///
    /// Run it from the menu (<b>Blackjack ▸ Build UI Scenes</b>) or headlessly:
    /// <code>
    /// Unity.exe -batchmode -projectPath "&lt;root&gt;" -logFile - \
    ///           -executeMethod BlackjackGame.EditorTools.SceneBootstrap.BuildAllFromCommandLine
    /// </code>
    /// It is idempotent: re-running overwrites the scenes and reuses existing config assets.
    /// </summary>
    public static class SceneBootstrap
    {
        // ---- Paths ----
        private const string ScenesFolder = "Assets/Scenes";
        private const string SettingsFolder = "Assets/Settings";
        private const string PrefabsFolder = "Assets/Prefabs";

        private const string MainMenuScenePath = ScenesFolder + "/MainMenu.unity";
        private const string GameScenePath = ScenesFolder + "/Game.unity";
        private const string StoreScenePath = ScenesFolder + "/Store.unity";

        private const string GameConfigPath = SettingsFolder + "/GameConfig.asset";
        private const string EconomyConfigPath = SettingsFolder + "/EconomyConfig.asset";
        private const string PackRowPrefabPath = PrefabsFolder + "/StorePackRow.prefab";
        private const string CardPrefabPath = PrefabsFolder + "/CardView.prefab";
        private const string CardLibraryPath = SettingsFolder + "/CardSpriteLibrary.asset";

        // Art generated by art-source/generate_card_art.py
        private const string CardArtFolder = "Assets/Art/Cards";
        private const string FeltSpritePath = "Assets/Art/Table/Felt.png";

        // Gold UI kit generated by art-source/generate_ui_kit.py
        private const string UiArtFolder = "Assets/Art/UI";

        // Table plate + sprites lifted from the concept render by
        // art-source/extract_table_art.py
        private const string TableBackgroundPath = "Assets/Art/Table/TableBackground.png";
        private const string StoreBackgroundPath = "Assets/Art/Table/StoreBackground.png";
        private const string MenuBackgroundPath = "Assets/Art/Table/MenuBackground.png";

        // ---- Concept-render coordinate mapping -------------------------------
        // docs/screenshots/game-table.png is 1024x1536; the game canvas is 1080x1920 with
        // the render scaled to width and pinned 110px down (see extract_table_art.py).
        // Laying the scene out in the render's own pixel coordinates means every element
        // lands exactly where the concept art put it.
        private const float SrcScale = 1080f / 1024f;
        private const float SrcTopPad = 110f;

        private static float SrcX(float x) => x * SrcScale - 540f;
        private static float SrcY(float y) => 960f - (SrcTopPad + y * SrcScale);

        // ---- Palette ----
        private static readonly Color Felt = new Color(0.043f, 0.180f, 0.129f);
        private static readonly Color Panel = new Color(0.031f, 0.129f, 0.094f);
        /// <summary>Panels over the felt art — translucent so the table reads through.</summary>
        private static readonly Color GlassPanel = new Color(0.016f, 0.086f, 0.063f, 0.55f);
        private static readonly Color Gold = new Color(0.949f, 0.769f, 0.310f);
        private static readonly Color ButtonFill = new Color(0.129f, 0.353f, 0.263f);
        private static readonly Color ButtonAccent = new Color(0.729f, 0.180f, 0.180f);
        private static readonly Color Ink = new Color(0.918f, 0.945f, 0.933f);

        // Glow colours for the table actions. Each is a brightened version of its own
        // button frame so the halo reads as that button lighting up, not as a stray
        // coloured rim — a gold glow on a red frame just looks like a rendering mistake.
        private static readonly Color HitGlow = new Color(0.42f, 1.00f, 0.52f);
        private static readonly Color StandGlow = new Color(1.00f, 0.44f, 0.40f);
        private static readonly Color DoubleGlow = new Color(0.44f, 0.72f, 1.00f);
        private static readonly Color SplitGlow = new Color(1.00f, 0.84f, 0.42f);

        private static readonly Vector2 ReferenceResolution = new Vector2(1080f, 1920f);

        // =====================================================================
        //  Entry points
        // =====================================================================

        [MenuItem("Blackjack/Build UI Scenes", priority = 0)]
        public static void BuildUIScenes()
        {
            BuildAll();
            EditorUtility.DisplayDialog(
                "Blackjack",
                "MainMenu, Game and Store scenes were rebuilt, wired and added to Build Settings.",
                "Nice");
        }

        [MenuItem("Blackjack/Verify Scene Wiring", priority = 1)]
        public static void VerifySceneWiringMenu()
        {
            var problems = VerifyWiring();
            if (problems.Count == 0)
            {
                Debug.Log("[SceneBootstrap] Wiring OK — every serialized reference is assigned.");
                EditorUtility.DisplayDialog("Blackjack", "All scenes are fully wired.", "Good");
            }
            else
            {
                Debug.LogError("[SceneBootstrap] Wiring problems:\n - " + string.Join("\n - ", problems));
                EditorUtility.DisplayDialog("Blackjack", $"{problems.Count} wiring problem(s). See Console.", "OK");
            }
        }

        /// <summary>Batch-mode entry point. Exits non-zero if anything goes wrong.</summary>
        public static void BuildAllFromCommandLine()
        {
            try
            {
                BuildAll();

                var problems = VerifyWiring();
                if (problems.Count > 0)
                {
                    Debug.LogError("[SceneBootstrap] FAILED — unwired references:\n - " +
                                   string.Join("\n - ", problems));
                    EditorApplication.Exit(2);
                    return;
                }

                Debug.Log("[SceneBootstrap] SUCCESS — scenes built, wired and registered in Build Settings.");
                EditorApplication.Exit(0);
            }
            catch (Exception e)
            {
                Debug.LogError($"[SceneBootstrap] FAILED — {e}");
                EditorApplication.Exit(1);
            }
        }

        /// <summary>Batch-mode entry point that only checks wiring (no rebuild).</summary>
        public static void VerifyFromCommandLine()
        {
            try
            {
                var problems = VerifyWiring();
                if (problems.Count > 0)
                {
                    Debug.LogError("[SceneBootstrap] Wiring problems:\n - " + string.Join("\n - ", problems));
                    EditorApplication.Exit(2);
                    return;
                }
                Debug.Log("[SceneBootstrap] Wiring OK.");
                EditorApplication.Exit(0);
            }
            catch (Exception e)
            {
                Debug.LogError($"[SceneBootstrap] FAILED — {e}");
                EditorApplication.Exit(1);
            }
        }

        // =====================================================================
        //  Build pipeline
        // =====================================================================

        public static void BuildAll()
        {
            EnsureFolder(ScenesFolder);
            EnsureFolder(SettingsFolder);
            EnsureFolder(PrefabsFolder);

            DeleteObsoleteBakedLabels();

            // Text is TextMeshPro now, so the font assets and gold materials have to exist
            // before any scene is built. Cheap no-op once they're there.
            if (AssetDatabase.LoadAssetAtPath<TMP_FontAsset>(FontAssetBuilder.DisplayAssetPath) == null)
                FontAssetBuilder.BuildAll();

            // Only guarantees the assets exist on disk. Do NOT hold the returned
            // references across a scene change — see RequireAsset below.
            EnsureAsset<GameConfig>(GameConfigPath);
            EnsureAsset<EconomyConfig>(EconomyConfigPath);
            EnsureAsset<CardSpriteLibrary>(CardLibraryPath);
            PopulateCardLibrary();
            CreateCardPrefab();

            BuildMainMenuScene();
            BuildGameScene();
            BuildStoreScene();

            RegisterBuildSettingsScenes();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        private static void BuildMainMenuScene()
        {
            Scene scene = NewScene();

            // Loaded AFTER NewScene(). Opening a new scene runs UnloadUnusedAssets, which
            // collects any asset held only by a plain C# local — a managed variable is not
            // a GC root as far as Unity's native object lifetime is concerned. Passing the
            // freshly-created ScriptableObjects in as arguments gives you a "fake null" here.
            GameConfig gameConfig = RequireAsset<GameConfig>(GameConfigPath);
            EconomyConfig economyConfig = RequireAsset<EconomyConfig>(EconomyConfigPath);

            // Composition root — persists across scene loads via MonoSingleton.
            var appManager = new GameObject("AppManager").AddComponent<AppManager>();
            Wire(appManager,
                ("_gameConfig", gameConfig),
                ("_economyConfig", economyConfig));

            Canvas canvas = CreateCanvas();
            Transform root = canvas.transform;
            // The crest, wordmark, tagline, house rules and corner props are all static,
            // so they stay part of the render rather than being rebuilt as UI objects.
            CreateBackground(root, Color.white, LoadSprite(MenuBackgroundPath));

            // ---- top bar: balance pill + quick-action circles -------------------
            CreateFrame(root, "BalancePill", "pill", new Vector2(-300f, 856f), new Vector2(400f, 104f));
            CreateSpriteImage(root, "CoinIcon", "icon_coin", new Vector2(-444f, 856f), 78f);
            CreateSpriteImage(root, "AddChipsIcon", "icon_plus", new Vector2(-154f, 856f), 46f);
            TMP_Text balanceLabel = CreateText(root, "BalanceLabel", "0",
                new Vector2(-294f, 856f), new Vector2(240f, 80f), 50f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);

            // Quick-action circles: gift (daily-reward shortcut), settings, stats.
            string[] quickIcons = { "icon_gift", "icon_settings", "icon_trophy" };
            string[] quickNames = { "Gift", "Settings", "Trophy" };
            var quickButtons = new Button[quickIcons.Length];
            for (int i = 0; i < quickIcons.Length; i++)
            {
                var at = new Vector2(SrcX(722f + i * 108f), SrcY(70f));
                quickButtons[i] = CreateCircleButton(root, $"Quick{quickNames[i]}", quickIcons[i], at, 100f);
            }

            // ---- action rows, on the render's own marks --------------------------
            Button playButton = CreateMenuRow(root, "PlayButton", "btn_green", "icon_cards",
                "PLAY", "DEAL YOUR LUCK", new Vector2(SrcX(513), SrcY(815)));
            Button storeButton = CreateMenuRow(root, "StoreButton", "btn_blue", "icon_cart",
                "STORE", "GET CHIPS & ITEMS", new Vector2(SrcX(513), SrcY(982)));
            Button rewardsButton = CreateMenuRow(root, "RewardsButton", "btn_red", "icon_gift",
                "DAILY REWARDS", "CLAIM YOUR PRIZE", new Vector2(SrcX(513), SrcY(1144)));

            TMP_Text rewardStatusLabel = CreateText(root, "RewardStatusLabel", "",
                new Vector2(SrcX(513), SrcY(1258)), new Vector2(940f, 60f), 32f,
                TextAlignmentOptions.Center, TextStyle.BodyInk);

            SettingsPanel settingsPanel = CreateSettingsPanel(root);
            StatsPanel statsPanel = CreateStatsPanel(root);

            var balanceRollup = balanceLabel.gameObject.AddComponent<CountRollup>();
            var rewardPunch = rewardStatusLabel.gameObject.AddComponent<LabelPunch>();

            var ui = canvas.gameObject.AddComponent<MainMenuUI>();
            Wire(ui,
                ("_playButton", playButton),
                ("_storeButton", storeButton),
                ("_rewardsButton", rewardsButton),
                ("_giftButton", quickButtons[0]),
                ("_settingsButton", quickButtons[1]),
                ("_trophyButton", quickButtons[2]),
                ("_settingsPanel", settingsPanel),
                ("_statsPanel", statsPanel),
                ("_balanceLabel", balanceLabel),
                ("_rewardStatusLabel", rewardStatusLabel),
                ("_balanceRollup", balanceRollup),
                ("_rewardPunch", rewardPunch));

            SaveScene(scene, MainMenuScenePath);
        }

        private static void BuildGameScene()
        {
            Scene scene = NewScene();

            new GameObject("GameManager").AddComponent<GameManager>();

            Canvas canvas = CreateCanvas();
            Transform root = canvas.transform;

            // The whole table — rail, chip tray, shoe, felt, arc text, spade medallion —
            // is the concept render itself with the dynamic bits inpainted out. Positions
            // below are the render's own, mapped through SrcX/SrcY.
            CreateBackground(root, Color.white, LoadSprite(TableBackgroundPath));

            // Everything except the background hangs off this wrapper so the screen shake
            // can move the table's contents without dragging the backdrop with it — a
            // shaking background would expose the canvas edges.
            GameObject shakeRoot = NewUIObject("Content", root);
            Stretch(shakeRoot);
            root = shakeRoot.transform;

            // --- top bar ---------------------------------------------------------
            // Back arrow, then the balance pill — the same arrangement the store render
            // uses. The pill is nudged right of the render's position so the two don't
            // collide: at the render's x they overlapped by ~50px.
            Button backButton = CreateCircleButton(root, "BackButton", "icon_back",
                new Vector2(SrcX(62), SrcY(70)), 100f);

            CreateFrame(root, "BalancePill", "pill",
                new Vector2(SrcX(300), SrcY(70)), new Vector2(360f, 96f));
            CreateSpriteImage(root, "CoinIcon", "icon_coin", new Vector2(SrcX(154), SrcY(70)), 72f);
            CreateSpriteImage(root, "AddChipsIcon", "icon_plus", new Vector2(SrcX(446), SrcY(70)), 42f);
            TMP_Text balanceLabel = CreateText(root, "BalanceLabel", "0",
                new Vector2(SrcX(304), SrcY(70)), new Vector2(200f, 72f), 46f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);

            Button giftButton = CreateCircleButton(root, "QuickGift", "icon_gift", new Vector2(SrcX(722), SrcY(70)), 100f);
            Button settingsButton = CreateCircleButton(root, "QuickSettings", "icon_settings", new Vector2(SrcX(830), SrcY(70)), 100f);
            Button trophyButton = CreateCircleButton(root, "QuickTrophy", "icon_trophy", new Vector2(SrcX(938), SrcY(70)), 100f);

            // --- dealer ----------------------------------------------------------
            HandView dealerHandView = CreateHandView(root, "DealerHandView",
                new Vector2(SrcX(516), SrcY(300)), new Vector2(172f, 241f));
            TMP_Text dealerHandLabel = CreateText(root, "DealerHandLabel", "Dealer",
                new Vector2(SrcX(512), SrcY(150)), new Vector2(700f, 60f), 40f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);

            // --- player ----------------------------------------------------------
            HandView playerHandView = CreateHandView(root, "PlayerHandView",
                new Vector2(SrcX(470), SrcY(828)), new Vector2(206f, 288f));
            TMP_Text playerHandLabel = CreateText(root, "PlayerHandLabel", "Place your bet",
                new Vector2(SrcX(512), SrcY(636)), new Vector2(820f, 60f), 40f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);

            // Bet chip sits to the right of the hand. HandView caps how wide a hand may
            // spread, so this clears the cards even on a heavily-hit hand — at the
            // render's own x it was overlapped by the third card onward.
            var betChipSpot = new Vector2(SrcX(900), SrcY(884));
            Image betChipImage = CreateSpriteImage(root, "BetChip", "chip_stack", betChipSpot, 150f);

            // The sprite's baked "100" is painted out by the art pipeline, so the stake is
            // drawn live here and stays correct after a double or a split. The label is a
            // child of the chip so it travels, spins and scales with it.
            TMP_Text betChipLabel = CreateText(betChipImage.transform, "BetChipLabel", "0",
                new Vector2(0f, betChipImage.rectTransform.sizeDelta.y * 0.04f),
                new Vector2(104f, 54f), 40f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);
            // Stakes run from two digits to seven, and the chip face is a fixed circle, so
            // let TMP shrink the number to fit rather than letting "50,000" hang off it.
            betChipLabel.enableAutoSizing = true;
            betChipLabel.fontSizeMin = 16f;
            betChipLabel.fontSizeMax = 40f;

            var betChip = betChipImage.gameObject.AddComponent<BetChipView>();
            Wire(betChip, ("_label", betChipLabel));
            // Chip flies out of, and back into, the balance pill in the top bar.
            var chipSo = new SerializedObject(betChip);
            chipSo.FindProperty("_flyFrom").vector2Value = new Vector2(SrcX(300), SrcY(70));
            chipSo.FindProperty("_loseTo").vector2Value = new Vector2(SrcX(516), SrcY(300));
            chipSo.ApplyModifiedPropertiesWithoutUndo();

            TMP_Text outcomeLabel = CreateText(root, "OutcomeLabel", "",
                new Vector2(SrcX(512), SrcY(1046)), new Vector2(1000f, 90f), 56f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);

            // --- control band: bet row and action row share the same strip ---------
            // HIT and STAND are the two moves a player makes on nearly every hand, so they
            // take the larger frames and the middle of the rail, where a thumb rests.
            // DOUBLE and SPLIT are situational and sit outboard, smaller.
            //
            // Sizes and spacing come from one rule rather than four hand-placed marks: the
            // gutter is whatever is left after the four buttons, split evenly. That keeps
            // the row balanced and symmetric if the sizes are ever retuned.
            float bandY = SrcY(1179);
            var primarySize = new Vector2(262f, 208f);
            var secondarySize = new Vector2(208f, 172f);
            const float bandMargin = 18f;

            // Left to right: DOUBLE, HIT, STAND, SPLIT.
            float[] widths = { secondarySize.x, primarySize.x, primarySize.x, secondarySize.x };
            float usedWidth = 0f;
            foreach (float w in widths) usedWidth += w;
            float gutter = (1080f - 2f * bandMargin - usedWidth) / (widths.Length - 1);

            var slots = new float[widths.Length];
            float cursor = -540f + bandMargin;
            for (int i = 0; i < widths.Length; i++)
            {
                slots[i] = cursor + widths[i] * 0.5f;
                cursor += widths[i] + gutter;
            }

            // Bet row: [-] [ amount ] [+]  then a wide DEAL. The steppers exist because
            // typing a number on a phone means opening a keyboard over the table; most
            // players just want to nudge the stake and deal.
            // No "BET" caption: the only clear space above the row is occupied by the
            // table's gold arc, and a label there collides with it. The steppers either
            // side of a number, next to DEAL, carry the meaning on their own.
            CanvasGroup betRow = CreateRow(root, "BetRow");

            Button betMinusButton = CreateActionButton(betRow.transform, "BetMinusButton", null, "-",
                new Vector2(-462f, bandY), new Vector2(108f, 132f), "btn_dark", SplitGlow);
            TMP_InputField betInput = CreateInputField(betRow.transform, "BetInput", "100",
                new Vector2(-242f, bandY), new Vector2(304f, 144f));
            Button betPlusButton = CreateActionButton(betRow.transform, "BetPlusButton", null, "+",
                new Vector2(-22f, bandY), new Vector2(108f, 132f), "btn_dark", SplitGlow);

            Button dealButton = CreateActionButton(betRow.transform, "DealButton", null, "DEAL",
                new Vector2(288f, bandY), new Vector2(424f, 176f),
                "btn_green", HitGlow);

            // Each action gets its own colour so it can be found by hue rather than by
            // reading four near-identical labels: green to take a card, red to stop,
            // blue to commit more chips, gold to break the hand in two.
            CanvasGroup actionRow = CreateRow(root, "ActionRow");
            Button doubleButton = CreateActionButton(actionRow.transform, "DoubleButton", "icon_double", "DOUBLE",
                new Vector2(slots[0], bandY), secondarySize, "btn_blue", DoubleGlow);
            Button hitButton = CreateActionButton(actionRow.transform, "HitButton", "icon_hit", "HIT",
                new Vector2(slots[1], bandY), primarySize, "btn_green", HitGlow);
            Button standButton = CreateActionButton(actionRow.transform, "StandButton", "icon_stand", "STAND",
                new Vector2(slots[2], bandY), primarySize, "btn_red", StandGlow);
            Button splitButton = CreateActionButton(actionRow.transform, "SplitButton", "icon_split", "SPLIT",
                new Vector2(slots[3], bandY), secondarySize, "btn_dark", SplitGlow);

            SettingsPanel settingsPanel = CreateSettingsPanel(root);
            StatsPanel statsPanel = CreateStatsPanel(root);

            // Juice. The shake lives on the content wrapper rather than the Canvas: a
            // ScreenSpaceOverlay canvas has its transform driven by the canvas system
            // every frame, so offsets written to it are discarded.
            var balanceRollup = balanceLabel.gameObject.AddComponent<CountRollup>();
            var outcomePunch = outcomeLabel.gameObject.AddComponent<LabelPunch>();
            ScreenShake shake = shakeRoot.AddComponent<ScreenShake>();

            var ui = canvas.gameObject.AddComponent<GameTableUI>();
            Wire(ui,
                ("_betInput", betInput),
                ("_dealButton", dealButton),
                ("_betMinusButton", betMinusButton),
                ("_betPlusButton", betPlusButton),
                ("_betRow", betRow),
                ("_actionRow", actionRow),
                ("_hitButton", hitButton),
                ("_standButton", standButton),
                ("_doubleButton", doubleButton),
                ("_splitButton", splitButton),
                ("_dealerHandView", dealerHandView),
                ("_playerHandView", playerHandView),
                ("_dealerHandLabel", dealerHandLabel),
                ("_playerHandLabel", playerHandLabel),
                ("_outcomeLabel", outcomeLabel),
                ("_balanceLabel", balanceLabel),
                ("_backButton", backButton),
                ("_giftButton", giftButton),
                ("_settingsButton", settingsButton),
                ("_trophyButton", trophyButton),
                ("_settingsPanel", settingsPanel),
                ("_statsPanel", statsPanel),
                ("_balanceRollup", balanceRollup),
                ("_outcomePunch", outcomePunch),
                ("_shake", shake),
                ("_betChip", betChip));

            SaveScene(scene, GameScenePath);
        }

        private static void BuildStoreScene()
        {
            Scene scene = NewScene();

            // Built inside the fresh scene so the temporary instance never dirties another one,
            // then re-loaded from disk so we hold a reference the asset pipeline knows about.
            CreatePackRowPrefab();
            var prefabGo = AssetDatabase.LoadAssetAtPath<GameObject>(PackRowPrefabPath);
            if (prefabGo == null)
                throw new InvalidOperationException($"Could not load prefab at {PackRowPrefabPath}");
            StorePackRow packRowPrefab = prefabGo.GetComponent<StorePackRow>();

            Canvas canvas = CreateCanvas();
            Transform root = canvas.transform;

            // "GET CHIPS", "TAP TO PURCHASE" and the corner chip stacks are static, so they
            // stay part of the render. Only the rows and the top bar are rebuilt live.
            CreateBackground(root, Color.white, LoadSprite(StoreBackgroundPath));

            Button backButton = CreateCircleButton(root, "BackButton", "icon_back",
                new Vector2(SrcX(62), SrcY(70)), 100f);
            CreateFrame(root, "BalancePill", "pill",
                new Vector2(SrcX(300), SrcY(70)), new Vector2(360f, 96f));
            CreateSpriteImage(root, "CoinIcon", "icon_coin", new Vector2(SrcX(154), SrcY(70)), 72f);
            CreateSpriteImage(root, "AddChipsIcon", "icon_plus", new Vector2(SrcX(446), SrcY(70)), 42f);
            TMP_Text balanceLabel = CreateText(root, "BalanceLabel", "0",
                new Vector2(SrcX(304), SrcY(70)), new Vector2(200f, 72f), 46f,
                TextAlignmentOptions.Center, TextStyle.DisplayGold);

            Button giftButton = CreateCircleButton(root, "QuickGift", "icon_gift", new Vector2(SrcX(722), SrcY(70)), 100f);
            Button settingsButton = CreateCircleButton(root, "QuickSettings", "icon_settings", new Vector2(SrcX(830), SrcY(70)), 100f);
            Button trophyButton = CreateCircleButton(root, "QuickTrophy", "icon_trophy", new Vector2(SrcX(938), SrcY(70)), 100f);

            // Pack rows are instantiated into this container at runtime by StoreUI. The
            // container spans exactly the band the render's four rows occupy.
            GameObject listGo = NewUIObject("PackList", root);
            Place(listGo, new Vector2(SrcX(512), SrcY(900)), new Vector2(960f, 960f));
            var layout = listGo.AddComponent<VerticalLayoutGroup>();
            layout.spacing = 16f;
            layout.padding = new RectOffset(0, 0, 0, 0);
            layout.childAlignment = TextAnchor.UpperCenter;
            layout.childForceExpandWidth = true;
            layout.childForceExpandHeight = false;
            layout.childControlWidth = true;
            layout.childControlHeight = false;

            TMP_Text statusLabel = CreateText(root, "StatusLabel", "",
                new Vector2(SrcX(512), SrcY(1420)), new Vector2(1000f, 80f), 38f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);

            TMP_Text storeDisclaimer = CreateText(root, "Disclaimer",
                "Chips are virtual and have no cash value.",
                new Vector2(SrcX(512), SrcY(1490)), new Vector2(1000f, 56f), 24f,
                TextAlignmentOptions.Center, TextStyle.BodyInk);
            storeDisclaimer.alpha = 0.5f;

            SettingsPanel settingsPanel = CreateSettingsPanel(root);
            StatsPanel statsPanel = CreateStatsPanel(root);

            var balanceRollup = balanceLabel.gameObject.AddComponent<CountRollup>();
            var statusPunch = statusLabel.gameObject.AddComponent<LabelPunch>();

            var ui = canvas.gameObject.AddComponent<StoreUI>();
            Wire(ui,
                ("_packListRoot", listGo.transform),
                ("_packRowPrefab", packRowPrefab),
                ("_balanceLabel", balanceLabel),
                ("_statusLabel", statusLabel),
                ("_backButton", backButton),
                ("_giftButton", giftButton),
                ("_settingsButton", settingsButton),
                ("_trophyButton", trophyButton),
                ("_settingsPanel", settingsPanel),
                ("_statsPanel", statsPanel),
                ("_balanceRollup", balanceRollup),
                ("_statusPunch", statusPunch));

            // Chip artwork array, one sprite per pack, in EconomyConfig order.
            var so = new SerializedObject(ui);
            SerializedProperty art = so.FindProperty("_packArtwork");
            art.arraySize = 4;
            for (int i = 0; i < 4; i++)
                art.GetArrayElementAtIndex(i).objectReferenceValue = UiSprite($"chips_{i}");
            so.ApplyModifiedPropertiesWithoutUndo();

            SaveScene(scene, StoreScenePath);
        }

        private static void RegisterBuildSettingsScenes()
        {
            EditorBuildSettings.scenes = new[]
            {
                new EditorBuildSettingsScene(MainMenuScenePath, true),
                new EditorBuildSettingsScene(GameScenePath, true),
                new EditorBuildSettingsScene(StoreScenePath, true),
            };
            Debug.Log("[SceneBootstrap] Build Settings: MainMenu, Game, Store.");
        }

        // =====================================================================
        //  Verification
        // =====================================================================

        /// <summary>
        /// Opens each scene and reports any serialized object reference that was left null,
        /// plus any missing scene/build-settings entry. Empty list == fully wired.
        /// </summary>
        public static List<string> VerifyWiring()
        {
            var problems = new List<string>();

            CheckScene(MainMenuScenePath, problems, typeof(AppManager), typeof(MainMenuUI),
                typeof(SettingsPanel), typeof(StatsPanel));
            CheckScene(GameScenePath, problems, typeof(GameManager), typeof(GameTableUI), typeof(HandView),
                typeof(SettingsPanel), typeof(StatsPanel));
            CheckScene(StoreScenePath, problems, typeof(StoreUI), typeof(SettingsPanel), typeof(StatsPanel));

            // The card faces live in an array, which the per-field scan below cannot see.
            var library = AssetDatabase.LoadAssetAtPath<CardSpriteLibrary>(CardLibraryPath);
            if (library == null) problems.Add($"Missing CardSpriteLibrary at {CardLibraryPath}.");
            else if (!library.IsComplete)
                problems.Add("CardSpriteLibrary is incomplete — some faces or the back are unassigned.");

            if (AssetDatabase.LoadAssetAtPath<GameObject>(CardPrefabPath) == null)
                problems.Add($"Missing card prefab at {CardPrefabPath}.");
            if (AssetDatabase.LoadAssetAtPath<GameObject>(PackRowPrefabPath) == null)
                problems.Add($"Missing store row prefab at {PackRowPrefabPath}.");
            if (AssetDatabase.LoadAssetAtPath<Sprite>(FeltSpritePath) == null)
                problems.Add($"Missing table felt sprite at {FeltSpritePath}.");

            foreach (string path in new[]
                     {
                         FontAssetBuilder.DisplayAssetPath, FontAssetBuilder.BodyBoldAssetPath,
                         FontAssetBuilder.BodyAssetPath, FontAssetBuilder.GoldMaterialPath,
                         FontAssetBuilder.GoldSmallMaterialPath, FontAssetBuilder.InkMaterialPath,
                         FontAssetBuilder.GoldGradientPath,
                     })
            {
                if (AssetDatabase.LoadAssetAtPath<Object>(path) == null)
                    problems.Add($"Missing font asset '{path}' — run Blackjack ▸ Rebuild Font Assets.");
            }

            string[] expected = { MainMenuScenePath, GameScenePath, StoreScenePath };
            EditorBuildSettingsScene[] registered = EditorBuildSettings.scenes;
            for (int i = 0; i < expected.Length; i++)
            {
                if (i >= registered.Length || registered[i].path != expected[i] || !registered[i].enabled)
                {
                    problems.Add($"Build Settings slot {i} should be an enabled '{expected[i]}'.");
                }
            }

            return problems;
        }

        private static void CheckScene(string scenePath, List<string> problems, params Type[] requiredComponents)
        {
            if (AssetDatabase.LoadAssetAtPath<SceneAsset>(scenePath) == null)
            {
                problems.Add($"Scene missing: {scenePath}");
                return;
            }

            Scene scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);

            foreach (Type type in requiredComponents)
            {
                // Include inactive: SettingsPanel/StatsPanel start deactivated (they're
                // modals hidden until Show() is called), and the default overload only
                // finds active objects — without this every fresh build "fails" wiring
                // verification despite being wired correctly.
                var found = Object.FindObjectsByType(type, FindObjectsInactive.Include, FindObjectsSortMode.None);
                if (found.Length == 0)
                {
                    problems.Add($"{scene.name}: no {type.Name} in the scene.");
                    continue;
                }

                foreach (Object o in found)
                {
                    if (o is Component component) CollectUnassignedFields(component, scene.name, problems);
                }
            }

            if (Object.FindFirstObjectByType<EventSystem>() == null)
                problems.Add($"{scene.name}: no EventSystem (UI would be unclickable).");
            if (Object.FindFirstObjectByType<Canvas>() == null)
                problems.Add($"{scene.name}: no Canvas.");
        }

        private static void CollectUnassignedFields(Component component, string sceneName, List<string> problems)
        {
            var so = new SerializedObject(component);
            SerializedProperty it = so.GetIterator();
            bool enterChildren = true;
            while (it.NextVisible(enterChildren))
            {
                enterChildren = false;
                if (it.propertyType != SerializedPropertyType.ObjectReference) continue;
                if (it.objectReferenceValue == null)
                    problems.Add($"{sceneName}: {component.GetType().Name}.{it.propertyPath} is not assigned.");
            }
        }

        // =====================================================================
        //  Asset / scene helpers
        // =====================================================================

        private static Scene NewScene()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var cameraGo = new GameObject("Main Camera", typeof(Camera));
            cameraGo.tag = "MainCamera";
            cameraGo.transform.position = new Vector3(0f, 0f, -10f);
            Camera camera = cameraGo.GetComponent<Camera>();
            camera.clearFlags = CameraClearFlags.SolidColor;
            camera.backgroundColor = Felt;
            camera.orthographic = true;

            new GameObject("EventSystem", typeof(EventSystem), typeof(StandaloneInputModule));

            return scene;
        }

        private static void SaveScene(Scene scene, string path)
        {
            if (!EditorSceneManager.SaveScene(scene, path))
                throw new InvalidOperationException($"Could not save scene to {path}");
            Debug.Log($"[SceneBootstrap] Built {path}");
        }

        /// <summary>
        /// Loads an asset that must already exist. Call this immediately before use rather
        /// than caching the reference across a scene load — see the note in BuildMainMenuScene.
        /// </summary>
        private static T RequireAsset<T>(string path) where T : ScriptableObject
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset == null)
                throw new InvalidOperationException(
                    $"Expected a {typeof(T).Name} at '{path}' but could not load it.");
            return asset;
        }

        private static T EnsureAsset<T>(string path) where T : ScriptableObject
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset != null) return asset;

            asset = ScriptableObject.CreateInstance<T>();
            AssetDatabase.CreateAsset(asset, path);
            AssetDatabase.SaveAssets();
            Debug.Log($"[SceneBootstrap] Created {typeof(T).Name} at {path}");
            return asset;
        }

        private static void EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return;

            string parent = Path.GetDirectoryName(folder)?.Replace('\\', '/');
            string leaf = Path.GetFileName(folder);
            if (string.IsNullOrEmpty(parent) || string.IsNullOrEmpty(leaf)) return;

            EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, leaf);
        }

        /// <summary>Assigns private [SerializeField] references without needing public setters.</summary>
        private static void Wire(Component target, params (string field, Object value)[] bindings)
        {
            var so = new SerializedObject(target);
            foreach ((string field, Object value) in bindings)
            {
                SerializedProperty prop = so.FindProperty(field);
                if (prop == null)
                    throw new InvalidOperationException(
                        $"{target.GetType().Name} has no serialized field named '{field}'. " +
                        "Did the script change?");
                if (value == null)
                    throw new InvalidOperationException(
                        $"{target.GetType().Name}.{field}: nothing to assign (value was null).");

                prop.objectReferenceValue = value;
            }
            so.ApplyModifiedPropertiesWithoutUndo();
        }

        // =====================================================================
        //  UI construction helpers
        // =====================================================================

        private static GameObject NewUIObject(string name, Transform parent)
        {
            var go = new GameObject(name, typeof(RectTransform));
            go.transform.SetParent(parent, false);
            return go;
        }

        private static RectTransform Place(GameObject go, Vector2 position, Vector2 size)
        {
            var rt = (RectTransform)go.transform;
            rt.anchorMin = new Vector2(0.5f, 0.5f);
            rt.anchorMax = new Vector2(0.5f, 0.5f);
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.anchoredPosition = position;
            rt.sizeDelta = size;
            return rt;
        }

        private static RectTransform Stretch(GameObject go, float padding = 0f)
        {
            var rt = (RectTransform)go.transform;
            rt.anchorMin = Vector2.zero;
            rt.anchorMax = Vector2.one;
            rt.pivot = new Vector2(0.5f, 0.5f);
            rt.offsetMin = new Vector2(padding, padding);
            rt.offsetMax = new Vector2(-padding, -padding);
            return rt;
        }

        private static Canvas CreateCanvas()
        {
            var go = new GameObject("Canvas", typeof(Canvas), typeof(CanvasScaler), typeof(GraphicRaycaster));
            var canvas = go.GetComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            var scaler = go.GetComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = ReferenceResolution;
            scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
            scaler.matchWidthOrHeight = 0.5f;

            return canvas;
        }

        private static Sprite LoadSprite(string path)
        {
            var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path);
            if (sprite == null)
                Debug.LogWarning($"[SceneBootstrap] No sprite at '{path}'. " +
                                 "Run art-source/generate_card_art.py, then reimport.");
            return sprite;
        }

        // ---- gold UI kit helpers -------------------------------------------

        /// <summary>
        /// Removes the label/title sprites that used to carry the gold text. They were
        /// replaced by live TextMeshPro, which is sharp at any size and can't be scaled
        /// wrong — the old sprites shipped their glyphs inside ~26px of transparent
        /// padding, so sizing by sprite height silently shrank the text.
        /// Goes through AssetDatabase so the .meta files go with them.
        /// </summary>
        private static void DeleteObsoleteBakedLabels()
        {
            if (!AssetDatabase.IsValidFolder(UiArtFolder)) return;

            int removed = 0;
            foreach (string guid in AssetDatabase.FindAssets("t:Texture2D", new[] { UiArtFolder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                string file = Path.GetFileName(path);
                if (file.StartsWith("label_", StringComparison.Ordinal) ||
                    file.StartsWith("title_", StringComparison.Ordinal))
                {
                    if (AssetDatabase.DeleteAsset(path)) removed++;
                }
            }

            // chip_stack was first written to Assets/Art/Table; it belongs with the kit.
            if (AssetDatabase.DeleteAsset("Assets/Art/Table/chip_stack.png")) removed++;
            if (AssetDatabase.DeleteAsset("Assets/Prefabs/PackButton.prefab")) removed++;

            // The drawn ".b56" button frames were superseded by ".b46" frames built from
            // the concept render. Both matching would make UiSprite's lookup ambiguous.
            foreach (string guid in AssetDatabase.FindAssets("btn_ t:Texture2D", new[] { UiArtFolder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (Path.GetFileName(path).Contains(".b56."))
                    if (AssetDatabase.DeleteAsset(path)) removed++;
            }

            if (removed > 0)
                Debug.Log($"[SceneBootstrap] Removed {removed} obsolete sprite(s).");
        }

        /// <summary>Loads a kit sprite by bare name; ".b&lt;N&gt;" nine-slice files resolve too.</summary>
        private static Sprite UiSprite(string name)
        {
            var sprite = AssetDatabase.LoadAssetAtPath<Sprite>($"{UiArtFolder}/{name}.png");
            if (sprite != null) return sprite;

            // Try the nine-sliced variants, whose filenames carry a border suffix.
            foreach (string guid in AssetDatabase.FindAssets($"{name} t:Sprite", new[] { UiArtFolder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                if (Path.GetFileName(path).StartsWith(name + ".b", StringComparison.Ordinal))
                    return AssetDatabase.LoadAssetAtPath<Sprite>(path);
            }

            throw new InvalidOperationException(
                $"UI sprite '{name}' not found in {UiArtFolder}. " +
                "Run 'python3 art-source/generate_ui_kit.py' from the project root.");
        }

        /// <summary>A nine-sliced frame (button background, pill, panel).</summary>
        private static Image CreateFrame(Transform parent, string name, string sprite,
            Vector2 position, Vector2 size)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);
            var image = go.AddComponent<Image>();
            image.sprite = UiSprite(sprite);
            image.type = Image.Type.Sliced;
            image.pixelsPerUnitMultiplier = 1f;
            image.raycastTarget = false;
            return image;
        }

        /// <summary>
        /// An icon or baked-label sprite. Give it a target height, or pass
        /// <paramref name="widthOverride"/> to size by width instead — the other
        /// dimension follows the sprite's aspect either way.
        /// </summary>
        private static Image CreateSpriteImage(Transform parent, string name, string sprite,
            Vector2 position, float height, float widthOverride = 0f)
        {
            Sprite s = UiSprite(sprite);
            float aspect = s.rect.width / s.rect.height;

            float width;
            if (widthOverride > 0f)
            {
                width = widthOverride;
                height = width / aspect;
            }
            else
            {
                width = height * aspect;
            }

            GameObject go = NewUIObject(name, parent);
            Place(go, position, new Vector2(width, height));
            var image = go.AddComponent<Image>();
            image.sprite = s;
            image.type = Image.Type.Simple;
            image.preserveAspect = true;
            image.raycastTarget = false;
            return image;
        }

        /// <summary>A button whose background is a nine-sliced gold frame.</summary>
        private static Button CreateFrameButton(Transform parent, string name, string sprite,
            Vector2 position, Vector2 size)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var image = go.AddComponent<Image>();
            image.sprite = UiSprite(sprite);
            image.type = Image.Type.Sliced;
            image.pixelsPerUnitMultiplier = 1f;

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            ColorBlock colors = button.colors;
            colors.normalColor = Color.white;
            colors.highlightedColor = new Color(1.10f, 1.10f, 1.10f, 1f);
            colors.pressedColor = new Color(0.80f, 0.80f, 0.80f, 1f);
            // Distinctly dimmer + desaturated so unavailable actions read at a glance.
            colors.disabledColor = new Color(0.42f, 0.44f, 0.42f, 0.75f);
            colors.fadeDuration = 0.08f;
            button.colors = colors;

            return button;
        }

        /// <summary>A full-canvas container with a CanvasGroup, used to swap control rows.</summary>
        private static CanvasGroup CreateRow(Transform parent, string name)
        {
            GameObject go = NewUIObject(name, parent);
            Stretch(go);
            return go.AddComponent<CanvasGroup>();
        }

        /// <summary>Round gold button from the kit, with a centred icon.</summary>
        private static Button CreateCircleButton(Transform parent, string name, string icon,
            Vector2 position, float diameter)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, new Vector2(diameter, diameter));

            var image = go.AddComponent<Image>();
            image.sprite = UiSprite("circle_button");
            image.type = Image.Type.Simple;

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            CreateSpriteImage(go.transform, "Icon", icon, Vector2.zero, diameter * 0.52f);
            go.AddComponent<ButtonJuice>();
            return button;
        }

        /// <summary>
        /// Table action button using the frame lifted from the concept render, with the
        /// render's own icon above a TMP label — matching the mockup's HIT/STAND/DOUBLE/SPLIT.
        ///
        /// Carries a glow behind the frame and a <see cref="ButtonJuice"/> that pulses it
        /// while the move is legal, so the available actions announce themselves and dead
        /// ones visibly recede.
        /// </summary>
        private static Button CreateActionButton(Transform parent, string name, string icon,
            string label, Vector2 position, Vector2 size,
            string frame = "btn_action", Color? glowTint = null)
        {
            Color tint = glowTint ?? Gold;

            // Glow is a SIBLING placed before the button, not a child of it. UGUI draws
            // children after their parent, so a child glow would cover the button face —
            // it has to precede the button in the parent's own draw order to sit behind.
            // It reuses the button's own nine-sliced frame art, oversized and tinted, so
            // the silhouette matches without needing a bespoke glow sprite.
            GameObject glowGo = NewUIObject($"{name}Glow", parent);
            Place(glowGo, position, size + new Vector2(34f, 34f));
            var glow = glowGo.AddComponent<Image>();
            glow.sprite = UiSprite(frame);
            glow.type = Image.Type.Sliced;
            glow.pixelsPerUnitMultiplier = 1f;
            glow.color = new Color(tint.r, tint.g, tint.b, 0f);
            glow.raycastTarget = false;

            Button button = CreateFrameButton(parent, name, frame, position, size);
            Transform t = button.transform;

            if (!string.IsNullOrEmpty(icon))
            {
                // Icon sits high with the label beneath it. Both are pushed a little
                // further apart than the render's own spacing, which was tuned for a
                // smaller button and left them crowding the centre at this size.
                CreateSpriteImage(t, "Icon", icon, new Vector2(0f, size.y * 0.16f), size.y * 0.40f);
                CreateText(t, "Label", label, new Vector2(0f, -size.y * 0.31f),
                    new Vector2(size.x - 16f, size.y * 0.32f), size.y * 0.21f,
                    TextAlignmentOptions.Center, TextStyle.DisplayGold, characterSpacing: 2f);
            }
            else
            {
                CreateText(t, "Label", label, Vector2.zero,
                    new Vector2(size.x - 20f, size.y * 0.5f), size.y * 0.30f,
                    TextAlignmentOptions.Center, TextStyle.DisplayGold, characterSpacing: 4f);
            }

            var juice = button.gameObject.AddComponent<ButtonJuice>();
            Wire(juice, ("_glow", glow));

            return button;
        }

        /// <summary>One main-menu row: gold frame, icon, TMP title + subtitle, chevron.</summary>
        private static Button CreateMenuRow(Transform parent, string name, string frame,
            string icon, string label, string subLabel, Vector2 position)
        {
            var size = new Vector2(888f, 176f);
            Button button = CreateFrameButton(parent, name, frame, position, size);
            Transform t = button.transform;

            CreateSpriteImage(t, "Icon", icon, new Vector2(-size.x / 2f + 96f, 0f), 76f);
            CreateSpriteImage(t, "Chevron", "icon_chevron", new Vector2(size.x / 2f - 78f, 0f), 54f);

            CreateText(t, "Label", label, new Vector2(20f, 24f), new Vector2(size.x - 220f, 74f),
                58f, TextAlignmentOptions.Center, TextStyle.DisplayGold, characterSpacing: 4f);
            CreateText(t, "SubLabel", subLabel, new Vector2(20f, -34f),
                new Vector2(size.x - 220f, 44f), 30f, TextAlignmentOptions.Center,
                TextStyle.BodyInk, characterSpacing: 4f);

            button.gameObject.AddComponent<ButtonJuice>();
            return button;
        }

        /// <summary>Full-canvas dim layer behind a modal panel — blocks clicks to whatever
        /// is underneath while the panel is open.</summary>
        private static void CreateBackdrop(Transform parent)
        {
            GameObject go = NewUIObject("Backdrop", parent);
            Stretch(go);
            var image = go.AddComponent<Image>();
            image.color = new Color(0f, 0f, 0f, 0.72f);
            image.raycastTarget = true;
        }

        /// <summary>
        /// Gear-icon modal: a sound on/off toggle and a confirm-guarded "Reset Progress"
        /// action. Starts inactive — <see cref="SettingsPanel.Show"/> activates it.
        /// </summary>
        private static SettingsPanel CreateSettingsPanel(Transform parent)
        {
            var size = new Vector2(720f, 640f);

            GameObject root = NewUIObject("SettingsPanel", parent);
            Stretch(root);

            CreateBackdrop(root.transform);

            GameObject frameGo = NewUIObject("Frame", root.transform);
            Place(frameGo, Vector2.zero, size);
            var frameImage = frameGo.AddComponent<Image>();
            frameImage.sprite = UiSprite("panel");
            frameImage.type = Image.Type.Sliced;
            frameImage.pixelsPerUnitMultiplier = 1f;
            Transform t = frameGo.transform;

            CreateText(t, "Title", "SETTINGS", new Vector2(0f, size.y / 2f - 70f),
                new Vector2(size.x - 80f, 80f), 46f, TextAlignmentOptions.Center,
                TextStyle.DisplayGold, characterSpacing: 3f);

            Button muteButton = CreateFrameButton(t, "MuteButton", "btn_dark",
                new Vector2(0f, 90f), new Vector2(520f, 110f));
            TMP_Text muteLabel = CreateText(muteButton.transform, "Label", "Sound: On",
                Vector2.zero, new Vector2(480f, 90f), 38f, TextAlignmentOptions.Center,
                TextStyle.DisplayGold);

            Button resetButton = CreateFrameButton(t, "ResetButton", "btn_red",
                new Vector2(0f, -60f), new Vector2(520f, 110f));
            TMP_Text resetLabel = CreateText(resetButton.transform, "Label", "Reset Progress",
                Vector2.zero, new Vector2(480f, 90f), 34f, TextAlignmentOptions.Center,
                TextStyle.DisplayGold);

            Button closeButton = CreateFrameButton(t, "CloseButton", "btn_dark",
                new Vector2(0f, -size.y / 2f + 90f), new Vector2(300f, 90f));
            CreateText(closeButton.transform, "Label", "CLOSE", Vector2.zero,
                new Vector2(260f, 70f), 34f, TextAlignmentOptions.Center, TextStyle.DisplayGold);

            // Springs the frame in each time the panel is enabled.
            frameGo.AddComponent<PanelPop>();

            var panel = root.AddComponent<SettingsPanel>();
            Wire(panel,
                ("_closeButton", closeButton),
                ("_muteButton", muteButton),
                ("_muteLabel", muteLabel),
                ("_resetButton", resetButton),
                ("_resetLabel", resetLabel));

            root.SetActive(false);
            return panel;
        }

        /// <summary>
        /// Trophy-icon modal: the player's own local stats (no server leaderboard exists).
        /// Starts inactive — <see cref="StatsPanel.Show"/> activates and refreshes it.
        /// </summary>
        private static StatsPanel CreateStatsPanel(Transform parent)
        {
            var size = new Vector2(720f, 760f);

            GameObject root = NewUIObject("StatsPanel", parent);
            Stretch(root);

            CreateBackdrop(root.transform);

            GameObject frameGo = NewUIObject("Frame", root.transform);
            Place(frameGo, Vector2.zero, size);
            var frameImage = frameGo.AddComponent<Image>();
            frameImage.sprite = UiSprite("panel");
            frameImage.type = Image.Type.Sliced;
            frameImage.pixelsPerUnitMultiplier = 1f;
            Transform t = frameGo.transform;

            CreateText(t, "Title", "YOUR STATS", new Vector2(0f, size.y / 2f - 70f),
                new Vector2(size.x - 80f, 80f), 46f, TextAlignmentOptions.Center,
                TextStyle.DisplayGold, characterSpacing: 3f);

            float rowY = size.y / 2f - 180f;
            const float rowGap = 74f;
            var rowSize = new Vector2(size.x - 140f, 56f);

            TMP_Text levelLabel = CreateText(t, "LevelLabel", "Level 1", new Vector2(0f, rowY),
                rowSize, 34f, TextAlignmentOptions.Center, TextStyle.BodyGold);
            rowY -= rowGap;
            TMP_Text handsLabel = CreateText(t, "HandsLabel", "Hands played: 0", new Vector2(0f, rowY),
                rowSize, 34f, TextAlignmentOptions.Center, TextStyle.BodyInk);
            rowY -= rowGap;
            TMP_Text winRateLabel = CreateText(t, "WinRateLabel", "Win rate: 0%", new Vector2(0f, rowY),
                rowSize, 34f, TextAlignmentOptions.Center, TextStyle.BodyInk);
            rowY -= rowGap;
            TMP_Text blackjacksLabel = CreateText(t, "BlackjacksLabel", "Blackjacks: 0", new Vector2(0f, rowY),
                rowSize, 34f, TextAlignmentOptions.Center, TextStyle.BodyInk);
            rowY -= rowGap;
            TMP_Text streakLabel = CreateText(t, "StreakLabel", "Daily streak: 0", new Vector2(0f, rowY),
                rowSize, 34f, TextAlignmentOptions.Center, TextStyle.BodyInk);

            Button closeButton = CreateFrameButton(t, "CloseButton", "btn_dark",
                new Vector2(0f, -size.y / 2f + 90f), new Vector2(300f, 90f));
            CreateText(closeButton.transform, "Label", "CLOSE", Vector2.zero,
                new Vector2(260f, 70f), 34f, TextAlignmentOptions.Center, TextStyle.DisplayGold);

            frameGo.AddComponent<PanelPop>();

            var panel = root.AddComponent<StatsPanel>();
            Wire(panel,
                ("_closeButton", closeButton),
                ("_levelLabel", levelLabel),
                ("_handsLabel", handsLabel),
                ("_winRateLabel", winRateLabel),
                ("_blackjacksLabel", blackjacksLabel),
                ("_streakLabel", streakLabel));

            root.SetActive(false);
            return panel;
        }

        private static Image CreateBackground(Transform parent, Color color, Sprite sprite = null)
        {
            GameObject go = NewUIObject("Background", parent);
            Stretch(go);
            var image = go.AddComponent<Image>();
            image.color = color;
            image.raycastTarget = false;
            if (sprite != null)
            {
                image.sprite = sprite;
                image.type = Image.Type.Simple;
                image.preserveAspect = false;
            }
            return image;
        }

        /// <summary>
        /// A HandView plus the child transform its cards are parented to. Splitting the
        /// two keeps the layout anchor independent of the component's own transform.
        /// </summary>
        private static HandView CreateHandView(Transform parent, string name, Vector2 position,
            Vector2? cardSize = null)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, new Vector2(960f, 260f));

            GameObject rootGo = NewUIObject("Cards", go.transform);
            Place(rootGo, Vector2.zero, Vector2.zero);

            var view = go.AddComponent<HandView>();
            var prefabGo = AssetDatabase.LoadAssetAtPath<GameObject>(CardPrefabPath);
            if (prefabGo == null)
                throw new InvalidOperationException($"Card prefab missing at {CardPrefabPath}");

            Wire(view,
                ("_library", RequireAsset<CardSpriteLibrary>(CardLibraryPath)),
                ("_cardPrefab", prefabGo.GetComponent<Image>()),
                ("_cardRoot", rootGo.GetComponent<RectTransform>()),
                ("_shadowSprite", UiSprite("card_shadow")));

            if (cardSize.HasValue)
            {
                var so = new SerializedObject(view);
                so.FindProperty("_cardSize").vector2Value = cardSize.Value;
                so.ApplyModifiedPropertiesWithoutUndo();
            }

            return view;
        }

        private static Image CreatePanel(Transform parent, string name, Vector2 position, Vector2 size,
            Color? color = null)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);
            var image = go.AddComponent<Image>();
            image.color = color ?? Panel;
            image.raycastTarget = false;
            return image;
        }

        /// <summary>
        /// The three text treatments in the game. Baked label sprites used to do this job;
        /// TMP does it live, stays sharp at any size, and can't get its scale wrong.
        /// </summary>
        public enum TextStyle
        {
            /// <summary>Serif display face, metallic gold, bevelled — titles and button labels.</summary>
            DisplayGold,
            /// <summary>Bold body face in gold — subtitles, house rules.</summary>
            BodyGold,
            /// <summary>Plain body face in warm off-white — status lines, disclaimers.</summary>
            BodyInk,
        }

        private static T RequireFontAsset<T>(string path) where T : Object
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset == null)
                throw new InvalidOperationException(
                    $"Missing '{path}'. Run Blackjack ▸ Rebuild Font Assets first.");
            return asset;
        }

        private static TMP_Text CreateText(
            Transform parent,
            string name,
            string content,
            Vector2 position,
            Vector2 size,
            float fontSize,
            TextAlignmentOptions alignment = TextAlignmentOptions.Center,
            TextStyle style = TextStyle.BodyInk,
            float characterSpacing = 0f,
            bool wrap = false)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var text = go.AddComponent<TextMeshProUGUI>();
            text.text = content;
            text.fontSize = fontSize;
            text.alignment = alignment;
            text.characterSpacing = characterSpacing;
            text.raycastTarget = false;
            text.textWrappingMode = wrap ? TextWrappingModes.Normal : TextWrappingModes.NoWrap;
            text.overflowMode = TextOverflowModes.Overflow;

            switch (style)
            {
                case TextStyle.DisplayGold:
                    text.font = RequireFontAsset<TMP_FontAsset>(FontAssetBuilder.DisplayAssetPath);
                    text.fontSharedMaterial = RequireFontAsset<Material>(FontAssetBuilder.GoldMaterialPath);
                    text.colorGradientPreset =
                        RequireFontAsset<TMP_ColorGradient>(FontAssetBuilder.GoldGradientPath);
                    text.enableVertexGradient = true;
                    break;

                case TextStyle.BodyGold:
                    text.font = RequireFontAsset<TMP_FontAsset>(FontAssetBuilder.BodyBoldAssetPath);
                    text.fontSharedMaterial = RequireFontAsset<Material>(FontAssetBuilder.GoldSmallMaterialPath);
                    text.colorGradientPreset =
                        RequireFontAsset<TMP_ColorGradient>(FontAssetBuilder.GoldGradientPath);
                    text.enableVertexGradient = true;
                    break;

                default:
                    text.font = RequireFontAsset<TMP_FontAsset>(FontAssetBuilder.BodyAssetPath);
                    text.fontSharedMaterial = RequireFontAsset<Material>(FontAssetBuilder.InkMaterialPath);
                    break;
            }

            return text;
        }

        private static Button CreateButton(
            Transform parent,
            string name,
            string label,
            Vector2 position,
            Vector2 size,
            Color fill)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var image = go.AddComponent<Image>();
            image.color = fill;

            var button = go.AddComponent<Button>();
            button.targetGraphic = image;

            ColorBlock colors = button.colors;
            colors.highlightedColor = Color.Lerp(fill, Color.white, 0.15f);
            colors.pressedColor = Color.Lerp(fill, Color.black, 0.2f);
            colors.disabledColor = new Color(fill.r, fill.g, fill.b, 0.35f);
            button.colors = colors;

            CreateText(go.transform, "Label", label, Vector2.zero,
                new Vector2(size.x - 16f, size.y - 16f),
                Mathf.Min(size.y * 0.34f, 52f), TextAlignmentOptions.Center,
                TextStyle.DisplayGold, characterSpacing: 2f);

            return button;
        }

        private static TMP_InputField CreateInputField(
            Transform parent,
            string name,
            string defaultValue,
            Vector2 position,
            Vector2 size)
        {
            GameObject go = NewUIObject(name, parent);
            Place(go, position, size);

            var background = go.AddComponent<Image>();
            background.sprite = UiSprite("pill");
            background.type = Image.Type.Sliced;
            background.pixelsPerUnitMultiplier = 1f;

            var input = go.AddComponent<TMP_InputField>();
            input.targetGraphic = background;
            input.contentType = TMP_InputField.ContentType.IntegerNumber;
            input.characterLimit = 9;

            // TMP_InputField needs its text area to be a child RectTransform with a mask,
            // otherwise the caret and text render outside the field.
            GameObject viewport = NewUIObject("Text Area", go.transform);
            Stretch(viewport, 22f);
            viewport.AddComponent<RectMask2D>();

            TMP_Text placeholder = CreateText(viewport.transform, "Placeholder", "Bet…",
                Vector2.zero, size - new Vector2(44f, 44f), 44f,
                TextAlignmentOptions.Center, TextStyle.BodyInk);
            placeholder.fontStyle = FontStyles.Italic;
            placeholder.color = new Color(0.78f, 0.76f, 0.68f, 0.7f);
            Stretch(placeholder.gameObject);

            TMP_Text text = CreateText(viewport.transform, "Text", string.Empty,
                Vector2.zero, size - new Vector2(44f, 44f), 48f,
                TextAlignmentOptions.Center, TextStyle.BodyGold);
            text.richText = false;
            Stretch(text.gameObject);

            input.textViewport = (RectTransform)viewport.transform;
            input.textComponent = text;
            input.placeholder = placeholder;
            input.text = defaultValue;

            return input;
        }

        /// <summary>
        /// Fills the CardSpriteLibrary asset from Assets/Art/Cards. File names encode the
        /// suit and rank so the mapping is mechanical: card_&lt;Suit&gt;_&lt;01..13&gt;.png,
        /// with Suit spelled exactly as the C# enum.
        /// </summary>
        private static void PopulateCardLibrary()
        {
            CardSpriteLibrary library = RequireAsset<CardSpriteLibrary>(CardLibraryPath);
            var so = new SerializedObject(library);

            SerializedProperty faces = so.FindProperty("_faces");
            faces.arraySize = CardSpriteLibrary.FaceCount;

            var missing = new List<string>();
            foreach (Suit suit in (Suit[])Enum.GetValues(typeof(Suit)))
            {
                for (int rank = 1; rank <= 13; rank++)
                {
                    string path = $"{CardArtFolder}/card_{suit}_{rank:00}.png";
                    var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(path);
                    if (sprite == null) missing.Add(path);

                    int index = CardSpriteLibrary.IndexOf(new Card(suit, (Rank)rank));
                    faces.GetArrayElementAtIndex(index).objectReferenceValue = sprite;
                }
            }

            var back = AssetDatabase.LoadAssetAtPath<Sprite>($"{CardArtFolder}/card_Back.png");
            if (back == null) missing.Add($"{CardArtFolder}/card_Back.png");
            so.FindProperty("_back").objectReferenceValue = back;

            so.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(library);

            if (missing.Count > 0)
            {
                throw new InvalidOperationException(
                    $"{missing.Count} card sprite(s) missing, first: {missing[0]}. " +
                    "Run 'python3 art-source/generate_card_art.py' from the project root. " +
                    "If the PNGs exist, they may have imported as Textures rather than " +
                    "Sprites — ArtImportSettings should prevent that.");
            }

            Debug.Log($"[SceneBootstrap] Card library populated ({CardSpriteLibrary.FaceCount} faces + back).");
        }

        /// <summary>The card template HandView clones. A plain Image, sized at runtime.</summary>
        private static void CreateCardPrefab()
        {
            EnsureFolder(PrefabsFolder);

            GameObject go = NewUIObject("CardView", null);
            Place(go, Vector2.zero, new Vector2(150f, 210f));
            var image = go.AddComponent<Image>();
            image.preserveAspect = true;
            image.raycastTarget = false;
            image.sprite = LoadSprite($"{CardArtFolder}/card_Back.png");

            GameObject saved = PrefabUtility.SaveAsPrefabAsset(go, CardPrefabPath);
            Object.DestroyImmediate(go);

            if (saved == null)
                throw new InvalidOperationException($"Could not save prefab to {CardPrefabPath}");

            Debug.Log($"[SceneBootstrap] Built {CardPrefabPath}");
        }

        /// <summary>
        /// Builds the row template StoreUI clones for each chip pack: the render's gold
        /// row frame, chip artwork, amount, bonus, price pill and BEST VALUE ribbon.
        /// </summary>
        private static void CreatePackRowPrefab()
        {
            EnsureFolder(PrefabsFolder);

            var size = new Vector2(944f, 216f);
            GameObject go = NewUIObject("StorePackRow", null);
            Place(go, Vector2.zero, size);

            var frame = go.AddComponent<Image>();
            frame.sprite = UiSprite("store_row");
            frame.type = Image.Type.Sliced;
            frame.pixelsPerUnitMultiplier = 1f;

            var button = go.AddComponent<Button>();
            button.targetGraphic = frame;
            ColorBlock colors = button.colors;
            colors.highlightedColor = new Color(1.10f, 1.10f, 1.10f, 1f);
            colors.pressedColor = new Color(0.82f, 0.82f, 0.82f, 1f);
            colors.disabledColor = new Color(0.45f, 0.47f, 0.45f, 0.8f);
            button.colors = colors;

            var layoutElement = go.AddComponent<LayoutElement>();
            layoutElement.preferredHeight = size.y;
            layoutElement.minHeight = size.y;

            Transform t = go.transform;
            Image chips = CreateSpriteImage(t, "ChipArt", "chips_0",
                new Vector2(-size.x / 2f + 150f, 0f), 176f);

            TMP_Text amount = CreateText(t, "Amount", "10,000", new Vector2(-20f, 12f),
                new Vector2(430f, 110f), 82f, TextAlignmentOptions.Center,
                TextStyle.DisplayGold);
            TMP_Text bonus = CreateText(t, "Bonus", "+5,000 BONUS", new Vector2(-20f, -58f),
                new Vector2(430f, 48f), 30f, TextAlignmentOptions.Center,
                TextStyle.BodyGold, characterSpacing: 3f);

            GameObject priceGo = NewUIObject("PriceButton", t);
            Place(priceGo, new Vector2(size.x / 2f - 150f, 0f), new Vector2(210f, 118f));
            var priceBg = priceGo.AddComponent<Image>();
            priceBg.sprite = UiSprite("btn_price");
            priceBg.type = Image.Type.Sliced;
            priceBg.pixelsPerUnitMultiplier = 1f;
            priceBg.raycastTarget = false;

            TMP_Text price = CreateText(priceGo.transform, "PriceLabel", "$1.99", Vector2.zero,
                new Vector2(190f, 90f), 52f, TextAlignmentOptions.Center, TextStyle.BodyInk);
            price.color = new Color(0.10f, 0.08f, 0.03f);

            Image badge = CreateSpriteImage(t, "BestValueBadge", "badge_best_value",
                new Vector2(-size.x / 2f + 62f, size.y / 2f - 58f), 150f);

            go.AddComponent<ButtonJuice>();

            var row = go.AddComponent<StorePackRow>();
            Wire(row,
                ("_button", button),
                ("_chipImage", chips),
                ("_amountLabel", amount),
                ("_bonusLabel", bonus),
                ("_priceLabel", price),
                ("_bestValueBadge", badge.gameObject));

            GameObject saved = PrefabUtility.SaveAsPrefabAsset(go, PackRowPrefabPath);
            Object.DestroyImmediate(go);
            if (saved == null)
                throw new InvalidOperationException($"Could not save prefab to {PackRowPrefabPath}");

            Debug.Log($"[SceneBootstrap] Built {PackRowPrefabPath}");
        }

        /// <summary>Human-readable dump of the current wiring — handy when debugging by hand.</summary>
        [MenuItem("Blackjack/Log Scene Wiring Report", priority = 20)]
        private static void LogReport()
        {
            var sb = new StringBuilder("[SceneBootstrap] Wiring report\n");
            List<string> problems = VerifyWiring();
            sb.AppendLine(problems.Count == 0
                ? "All serialized references assigned."
                : string.Join("\n", problems));
            sb.AppendLine("Build Settings:");
            foreach (EditorBuildSettingsScene s in EditorBuildSettings.scenes)
                sb.AppendLine($"  [{(s.enabled ? "x" : " ")}] {s.path}");
            Debug.Log(sb.ToString());
        }
    }
}
